### ISSUE TITLE
typemap has no effect in CSV.read in Jupyter Notebook

### ISSUE THREAD

**Issue by shuofanzhang** [JuliaData/CSV.jl#1024]
CSV.read(HTTP.get("https://raw.githubusercontent.com/shuofanzhang/covid/main/Test_pos_over_time.csv").body,
                        DataFrame;
                        footerskip=2, 
                        select = [1, 2, 6], 
                        typemap = Dict(Float64 => String),
                        dateformat= "yyyy-mm-dd")

Try above code in Jupyter Notebook (6.4.8) with CSV v0.8.5, the resulting columns are not String but Float64.

<img width="369" alt="Screen Shot 2022-09-12 at 1 14 19 AM" src="https://user-images.githubusercontent.com/20671163/189578659-4c4d8dfc-7de0-4aa3-a878-c8a482853de5.png">

But the same codes works as expected in VS Code.

**Comment by nickrobinson251** [comment]
most likely in the VS Code environment a newer version of CSV.jl is being used. The latest version is v0.10. At this point v0.8 is relatively out-dated and in general we do not backport bugfixes to old versions. Is it possible for you to update to CSV.jl v0.10?

**Comment by shuofanzhang** [comment]
> 

I see, I just downloaded the newest Julia on my new laptop, so I thought everything was the latest.

It seems like I cannot update the CSV package, I get this information when I do status --outdated

![Screen Shot 2022-09-12 at 7 49 11 PM](https://user-images.githubusercontent.com/20671163/189778154-47fe87fb-0681-490e-b6ad-4bd1fdb2204d.png)

But I am not sure how to fix it...

**Comment by quinnj** [comment]
It's not the clearest, but in the yellow (green?) text after `CSV v0.8.5` it says `Forecast`, so that tells you the package that is "holding you back". I've made a PR [here](https://github.com/viraltux/Forecast.jl/pull/74) to update that package to be compatible w/ 1.0. Once we get CSV.jl 1.0 tagged, that should help these kinds of packages stay more up to date since they can just put compat at `CSV: "1"` and be done for a long time.
