### ISSUE TITLE
Error loading csv file with string of length 8

### ISSUE THREAD

**Issue by gbarz** [JuliaData/CSV.jl#1036]
When trying to load a simple CSV file with the function: "CSV.read(testfile, DataFrame")

where testfile is a the following trivial csv:

A,B
name, 1.0
longname, 1.0

I receive the following error:

ERROR: MethodError: Cannot convert an object of type
Parsers.Result{String15} to an object of type
Parsers.Result{Any}

However, when 'longname' is shortened by 1 character, the CSV.read function works fine.

I am running Julia 1.8.2 and CSV v0.10.4 on an M1 Mac with MacOS 12.6

**Comment by nickrobinson251** [comment]
this is due to an issue in InlineStrings.jl v1.2.1 -- InlineStrings.jl is a dependency of CSV.jl and is used for small string types. The issue is fixed in InlineStrings.jl v1.2.2, which should already be available. Please try updating the dependencies with `using Pkg; Pkg.update()`


`Pkg.status("InlineStrings"; mode=PKGMODE_MANIFEST)` can show you which version you have.

If that `Pkg.update()` doesn't get you v1.2.2, could you try starting Julia with the environment variable
`JULIA_PKG_SERVER_REGISTRY_PREFERENCE=eager` then hopefully that'll get you v1.2.2 🤞 
e.g.
```
$> JULIA_PKG_SERVER_REGISTRY_PREFERENCE=eager julia --project -q
julia> using Pkg; Pkg.update()
```

Alternatively, a workaround is to pass `stringtype=String`, like `CSV.read(testfile, DataFrame; stringtype=String)`

**Comment by gbarz** [comment]
Thank you for the prompt response.  As you noted, updating to InlineStrings.jl 1.2.2 fixed the issue.
