### ISSUE TITLE
Quotes around strings and vectors

### ISSUE THREAD

**Issue by vvjn** [JuliaData/CSV.jl#119]
When I save a `DataFrame` with strings in cells or vectors in cells, `CSV.write` doesn't put `"` quotes around the strings or vectors like `DataFrames.writetable` does. Ex:

```
df = DataFrame(A = 1:3, B = [4,6.0,2], C = ["a","b","c"], D = [[4,5],[3,3],[4,4]])
CSV.write("x.csv", df)
```

`x.csv` doesn't have quotes around the cells
```
A,B,C,D
1,4.0,a,[4, 5]
2,6.0,b,[3, 3]
3,2.0,c,[4, 4]
```

And it gets read in wrong when you it back `CSV.read("x.csv")`, because of the commas inside the square brackets.

**Comment by nalimilan** [comment]
Note that even if quotes were added, the arrays would be read back as strings, not as arrays. CSV does not support storing values other than scalars.

But I agree it would be better to add quotes here.

**Comment by vvjn** [comment]
Yes, it would be better to add quotes, especially around strings since commas inside strings ruin the csv file structure. And I use csv files so that the data can be used in other languages, so string quotes around vectors would be useful in that case.

**Comment by dawbarton** [comment]
There seems to be a more general (related) quoting problem - 
```
df = DataFrame(A="h,a", B=2)
CSV.write("out.csv", df)
```
results in
```
A,B
h,a,2
```
Furthermore, telling CSV.jl to add quotes to everything `CSV.write(joinpath(dir,"out.csv"), df; quotefields=true)` (not ideal since then integers become strings) yields
```
34A34,34B34
"h,a","2"
```
which isn't right for other reasons!

**Comment by dawbarton** [comment]
The issue seems to be that the quote character, escape character and delimiter are all stored as UInt8 rather than Char, hence when the function [`quoted`](https://github.com/JuliaData/CSV.jl/blob/2101155936396c348c85e33dbc331edf83ca0d08/src/Sink.jl#L20) checks for the existence of delimiters in the string it always fails. For example,
```
',' in "Hello, world" == true
(',' % UInt8) in "Hello, world" == false
```
As such, `quoted` always fails to quote.

A separate issue arises when quoting is enforced, in that case the string is constructed in [`quoted`](https://github.com/JuliaData/CSV.jl/blob/2101155936396c348c85e33dbc331edf83ca0d08/src/Sink.jl#L19) with `string(q, replace(val, q, string(e, q)), q)` and since `q` is a UInt8 it inserts it as a number.

In the [`streamto!`](https://github.com/JuliaData/CSV.jl/blob/2101155936396c348c85e33dbc331edf83ca0d08/src/Sink.jl#L50) function the quote characters are converted back to characters and so it's only the writing of the header that is (wrongly) affected when quoting is enforced.

Both these issues are quite easy to fix, but it's not clear to me what the correct fix is (there are several options, all straightforward). I'm not sure why `UInt8` is used as the storage type for the delimiters, escape characters, etc, and not Char - at one level that would be the easiest fix (though the most invasive). Otherwise we have a repeated conversions from UInt8 to Char.

**Comment by dawbarton** [comment]
I've submitted a fix of both these issues following the pattern already existing in the code of converting the delimiters/quoting/escape characters to Chars whenever needed.
