### ISSUE TITLE
Assume columns can have missing values by default

### ISSUE THREAD

**Issue by cynddl** [JuliaData/CSV.jl#153]
The current behavior of _CSV.jl_ is to scan columns until ```row_for_type_detect``` iterations have passed and infer their type.

However, for large files with few null cells, this force to set ```row_for_type_detect``` to the maximum number of rows, as the heuristic cannot detect if the last row of the file might contain null cells for instance.

--------

### Solution

One workaround would be to assume that rows can contain null cells by default, except if the user disable it. This was the behavior in ```DataFrames.readtable``` for instance.

Another would be to have a manual flag in ```CSV.Options``` to assume that all rows can contain null values.

**Comment by nalimilan** [comment]
I think `nullable` should accept three values, e.g. `:all`, `:auto`, `:none`. In the long term it would be nice to widen the column type as soon as a missing value is detected (due to the way arrays with missing values are stored, it should be possible to do that without copying already parsed values).

**Comment by nalimilan** [comment]
After discussing this with @quinnj, we agreed that assuming columns can contain missing values was the right default. I've prepared https://github.com/JuliaData/CSV.jl/pull/173 to change this.
