### ISSUE TITLE
Return DataArrays by default

### ISSUE THREAD

**Issue by matthieugomez** [JuliaData/CSV.jl#160]
I think that `CSV` should return DataArrays by default when returning a `Dataframe`.

The current experience for a user is really not friendly. For instance, this stuff returns an error in Julia but works in virtually any statistical language.
```julia
df = CSV.read(myfile)
df[1, 1] = missing
MethodError: Cannot `convert` an object of type Missings.Missing to an object of type Float64
This may have arisen from a call to the constructor Float64(...),
since type constructors fall back to convert methods.
```
When doing actual data analysis, missing values are the norm, not the exception.

**Comment by nalimilan** [comment]
When missing values are the norm, columns contain missing values, so they will be `Array{Union{T, Missing}}`. What's the actual use case where you've encountered this?

**Comment by matthieugomez** [comment]
Sentinel value in CSV(like -1) that should be transformed to missing

**Comment by nalimilan** [comment]
In that case you can do `df[1] = replace(df[1], -1 => missing)` (only on Julia 0.7, you can use `Missings.allowmissing` and/or `CategoricalArrays.recode` on 0.6). That sounds quite natural to me. It would also be possible to extend the `null` argument so that you can pass it a dict mapping columns to strings which should be considered as missing, so that the recoding is done directly on import (https://github.com/JuliaData/CSV.jl/issues/42).

It's been requested several times (including by core developers) that DataFrames columns do not allow for missing values by default, as it slows things down unnecessarily, and it's a good protection when you don't want to allow for missing values in a column.

**Comment by nalimilan** [comment]
See also https://github.com/JuliaData/CSV.jl/issues/153.

**Comment by nalimilan** [comment]
Closing in favor of https://github.com/JuliaData/CSV.jl/issues/153.

**Comment by deszoeke** [comment]
I have this problem in converse. I define a data frame with missing values, because they are missing before I calculate them. My program loops through experiments, calculates results, and fills them into the data table: 
```
df=DataFrame(:case => ["A","B"], :result => missing)
icase=1
# ...calculate a result...
result=5
df[:result][icase]=result
```
But the last line gives
```
ERROR: MethodError: Cannot `convert` an object of type Int64 to an object of type Missings.Missing
This may have arisen from a call to the constructor Missings.Missing(...),
since type constructors fall back to convert methods.
```
The problem seems to be that `typeof(df[:result])` is `Array{Missings.Missing,1}` and DataFrames doesn't promote it to `Union{T, Missing}` as needed.

**Comment by nalimilan** [comment]
> The problem seems to be that typeof(df[:result]) is Array{Missings.Missing,1} and DataFrames doesn't promote it to Union{T, Missing} as needed.

I'm not sure we want to allocate a new array automatically. Even R doesn't do that (it creates a Boolean column if you pass `NA`). You can allocate a column with the right type via e.g. `df[:result] = missings(Int, nrows(df))`.

Anyway that's completely unrelated to CSV.jl.
