### ISSUE TITLE
Change default escapechar='"'

### ISSUE THREAD

**Issue by heaven00** [JuliaData/CSV.jl#166]
Datafile = train.csv from [here](https://www.kaggle.com/c/jigsaw-toxic-comment-classification-challenge/data)

**Versions**
Julia 0.6.2
CSV 0.2.1+

**Description**
While reading the file its not able parse `\"` because of the default escapechar='\\' in the textual content within the 2nd column .i.e. `comment_text`
**Suggested solution**
set `escapechar='"'` which worked on julia 0.7 and julia 0.6 but only on @quinnj machine.

I am running Manjaro which is an archlinux flavour, any help would be appreciated :)

**Workaround**
So i tried using the `readdlm` that worked nicely for me 
```DataFrame(readdlm("data/train.csv", ','; skipstart=1), [:id, :comment_text, :toxic, :severe_toxic, :obscene, :threat, :insult, :identity_hate])```

**Comment by nalimilan** [comment]
TextParse.jl/CSVFiles.jl, R, dplyr/readr and Pandas use `""` to represent a quote inside a quoted field by default, which is consistent with the "[CSV standard](https://tools.ietf.org/html/rfc4180)".

@quinnj Do you confirm you're OK with switching to `escapechar='"'` by default? Though other implementations seem to handle double quotes via a separate argument, but it's not clear to me whether there's an advantage to doing so.

**Comment by nalimilan** [comment]
An interesting reference is W3C's [Model for Tablular Data on the Web](https://www.w3.org/TR/tabular-data-model/#parsing). It recommends using the quote as the escape char by default, so that double quotes are interpreted as single quotes inside quoted fields. Their escape char only escapes quotes, not other sequences. So maybe by default we should only treat double quotes as single quotes, but not interpret other escape sequences in any special way.

**Comment by nalimilan** [comment]
See https://discourse.julialang.org/t/problem-related-to-csv-read-and-strings/9595/8 for more examples.
