### ISSUE TITLE
Need skiprows::Int keyword argument for CSV.read

### ISSUE THREAD

**Issue by gtollefson** [JuliaData/CSV.jl#182]
I would like to read a file into a DataFrame while skipping a number of rows at the start of the file. I know an option exists to skip footer rows. This seems like a basic feature offered in DataFrames.jl that is not supported in CSV.jl and haven't been able to find any mention of it in docs or forums. Does this exist?

**Comment by davidanthoff** [comment]
You might be able to use the ``datarow`` option for that?

If that doesn't work, [CSVFiles.jl](https://github.com/davidanthoff/CSVFiles.jl) provides a ``skiplines_begin`` option.

**Comment by davidanthoff** [comment]
The one thing that was not clear to me from the doc is how it interacts with headers, maybe the language there could just be clarified.

**Comment by quinnj** [comment]
Yeah, it's a bit confusing mainly because `header` can be a few different things; the actual column names (as a vector), a single number (the row the column names are on), a range (multiple rows to combine as column names). `datarow` always seemed pretty self-explanatory to me (i.e. the row the data starts on), but I realize that a lot of other languages/packages use the skip terminology. I'm open to clarifications/api changes if something seems particularly better to everyone.
