### ISSUE TITLE
Feature request: separate missing indicator for non-parsable fields

### ISSUE THREAD

**Issue by bkamins** [JuliaData/CSV.jl#283]
I do not have a very strong case here, but my intuition is that it would be good to have a separate option for missing in a fields that is parsed (e.g. `Float64` or `Int`) and a separate option for field that is not parsed (i.e. ends up being a string).

The rationale is that a string indicating missing in `Int` column, e.g. `"NA"` can be a valid entry in a `String` column.

The extreme could be even to not to create `missing`s for string columns at all (and leave the user to decide what to do, as even for default `""` missing indicator I can imagine data sets where `""` is a valid string entry).

**Comment by quinnj** [comment]
> The rationale is that a string indicating missing in Int column, e.g. "NA" can be a valid entry in a String column.

Hmmm, I don't think I'm sold on this reason; if you're using `"NA"` as missing for your Int column, I think you'd expect it to represent missing for your string column as well.

csv as a data format is actually nice because it has a single, canonical way to represent missingness: ",,", i.e. two consecutive delimiters. It's the absence of a value, which fits well semantically for missingness and has the benefit of working no matter the column type.

Now, obviously a lot of people go and mess that nice way of representing missingness up by putting things like "NA" in place, which then makes it hard on parsers because they have to not only check for the nice, "empty" case, but also the possibility of an arbitrary string (or in the case of a recent enhancement, _multiple_ arbitrary strings).

At the end of the day, I can _kinda_ see where this is coming from, but I'm also not sure it's really worth pursuing. It'd be helpful if there were some more concrete cases where this kind of feature was really needed or desirable, because as-is, I think the argument is weak at best (certainly compared to the cost of implementing).

**Comment by bkamins** [comment]
I agree, that is why I have said that I do not have a very strong argument here.

The issue is that saving the following object `DataFrame(x=["", missing])` to a file and reading it back will produce `DataFrame(x=[missing, missing])`. Again - it is not a very strong case.

We could distinguish `,"",` and `,,` while parsing (the first is an empty string, the second is `missing`). This is what R does when writing CSVs (although when reading them back it disregards this and treats both options as `NA`).

But again - I do not have a very strong preference here so I am OK if you close this issue.

**Comment by quinnj** [comment]
I think I'm ok with parsing `,"",` as empty string; the only case I'd be worried about is if they somehow had logic that quoted _every_ string in a column and meant to have `,"",` be `missing`.

**Comment by bkamins** [comment]
OK. Let us close it - if users come back with this problem we know what to do (I R they live with this for years so probably it is better to focus efforts on different issues in CSV.jl for now 😄 )
