### ISSUE TITLE
Validate delim, quotechar, openquotechar and closequotechar and missingstring

### ISSUE THREAD

**Issue by bkamins** [JuliaData/CSV.jl#288]
Try reading and writing the following data frame:
```
 DataFrame(x=[",",","])
```
using `quotechar=','` to see the problem.

What rules I would recommend to check (maybe something more, maybe something is already checked and I have misssed it):
* `delim` can be anything except `\n` and `\r` (this is checked I guess - right);
* `quotechar`, `openquotechar` and `closequotechar` cannot be `delim` or `\n` or `\r`
* `missingstring` may not contain `delim`, `quotechar`, `openquotechar` or `closequotechar`, `\n` nor `\r` (now it throws an error if it does)
* additionally the question is if `openquotechar` is escaped in quoted sequence - I guess it is always escaped - right?
* maybe also `escapechar` requires some rules (but maybe not as it is used only inside quoted sequences)

**Comment by bkamins** [comment]
👍

We can leave it as is.

Sorry to bother you but have you checked if we as safe against the case when people could run `CSV.write` in several green threads e.g. using `@async` but on one OS thread. Then the buffer could still get corrupted in some cases, see https://docs.julialang.org/en/stable/manual/faq/#Asynchronous-IO-and-concurrent-synchronous-writes-1, and in particular:
>  the writing of each argument yields to other tasks while waiting for that part of the I/O to complete.

**Comment by quinnj** [comment]
It's a good point to bring up and after studying it for a while, I don't know that there's a great answer provided by the language really. With the refactoring in #286, the only place I think we'd really be in danger is when we have to escape a value when writing out, since we do several consecutive `Base.write` calls that might trigger a `yield()`. In general though, we're safe because from writing to the buffer to writing out to the `IO` there isn't any additional IO in between that might trigger overwrites.

**Comment by bkamins** [comment]
Let us revert in this issue to the original problem - i.e. validation of keyword arguments. Sorry for mixing up.

**Comment by quinnj** [comment]
Should be covered by https://github.com/JuliaData/Parsers.jl/pull/29

**Comment by quinnj** [comment]
Implemented in https://github.com/JuliaData/Parsers.jl/pull/29
