### ISSUE TITLE
Compile times

### ISSUE THREAD

**Issue by gdkrmr** [JuliaData/CSV.jl#296]
Compile times often dominate reading times (12s vs. 3s in the most extreme case I observed) if the csv has many columns. Reading a csv file usually is a one time thing and therefore compile time is an important factor here. I am not sure if you can do anything about this, just something you may want to keep in mind when benchmarking.

**Comment by quinnj** [comment]
Please share specific examples; this has been addressed several times in the last few weeks, so things should be better, but if you have specific cases where compilation is bad, we can only do something about it with a reproducible example.

**Comment by gdkrmr** [comment]
Sorry for that, there are probably limits for what you can actually do about this, you can find the files I used [here](http://databank.worldbank.org/data/download/WDI_csv.zip):
```julia
julia> using DataFrames
julia> using CSV
julia> @time x = "WDIData.csv" |> CSV.File |> DataFrame;
  6.684520 seconds (58.74 M allocations: 1.736 GiB, 10.81% gc time)

julia> @time x = "WDIData.csv" |> CSV.File |> DataFrame;
  3.817177 seconds (41.51 M allocations: 1013.446 MiB, 7.96% gc time)

julia> @time x = "WDICountry.csv" |> CSV.File |> DataFrame;
  0.226692 seconds (312.24 k allocations: 14.160 MiB)

julia> @time x = "WDICountry.csv" |> CSV.File |> DataFrame;
  0.031184 seconds (16.59 k allocations: 475.586 KiB)

julia> @time x = "WDISeries.csv" |> CSV.File |> DataFrame;
  0.753752 seconds (3.58 M allocations: 161.486 MiB, 6.10% gc time)

julia> @time x = "WDISeries.csv" |> CSV.File |> DataFrame;
  0.088906 seconds (93.93 k allocations: 2.280 MiB)
```

**Comment by wusunlab** [comment]
I have the same issue. I was reading a CSV file of 1.5 MB and it took 9 seconds to compile and ate 1 GB during allocation. (In comparison, `pandas` can do a split second because the low-level work is done by pre-compiled C/C++.)

I understand that the compilation time is a feature of the Julia language. However, in practical use settings, when you just read a file once, waiting for it to compile is not very convenient.

**Comment by quinnj** [comment]
I did some experimentation last night to find the right threshold of when we should dynamically compile a specialized parsing kernel vs. not. This isn't perfect, because it depends on hard to control factors like performance of an individual machine, Base julia compile times, types and ordering of columns in a file, but things should be better on master/current release now. Here's the PR for reference: https://github.com/JuliaData/CSV.jl/pull/303. The idea is that at some point, there's a threshold of when the dynamic cost of compilation is worth the extra parsing speedup; I've currently set this threshold at 500K cells for a csv file. We can obviously revisit/adjust this as needed.
