### ISSUE TITLE
Cannot read datetime

### ISSUE THREAD

**Issue by getzze** [JuliaData/CSV.jl#310]
```
(v1.0) pkg> st
    Status `~/.julia/environments/v1.0/Project.toml`
  [336ed68f] CSV v0.4.1
  [a93c6f00] DataFrames v0.14.0
```

Minimal code to reproduce the error:
```julia
df = DataFrame(event = ["StartMovie", "Type"], time = ["2018-09-20T18:00:30.12345+00:00", "2018-09-20T18:02:13.67188+00:00"], type=["Event", "Event"] )
CSV.write("test.csv", df)
dfo = CSV.read("test.csv")
```
I get an `ERROR: InexactError: convert(Dates.Decimal3, 12345)`.
It tries to format the date and fails but the error is propagated.
Even adding a `transforms=Dict(2=>fun)` kwargs to parse the problematic date results in an error.

**Comment by quinnj** [comment]
Sorry, forgot to comment when this closed; there are actually two things going on here. First, we were obviously throwing an error when _attempting_ to parse the DateTime, which was bad because it totally killed parsing. That's the actual fix that went in the commit (45ad735). The error comes from the fact that `.12345` is invalid for current Julia DateTime values because it only supports up to millisecond precision (3 digits).
