### ISSUE TITLE
Missing Bug

### ISSUE THREAD

**Issue by iwelch** [JuliaData/CSV.jl#319]
I am going to presume that CSV should be able to eat its own dogfood:

```
using DataFrames

const xl= vcat( collect( 1:30_000 ), missing );
const df= DataFrame( x=xl, n= string.( xl .+ xl/10 ), i= string.( xl ), f=sqrt.(xl), f2=log.(xl) );

using CSV
csvfname= "/tmp/wdfname.csv"
CSV.write(csvfname, df)
x= CSV.read(csvfname)
println("File Size of $csvfname: $(filesize(csvfname))\n")

```

```
julia> include("t.jl")
warning: failed parsing Float64 on row=30001, col=2, error=INVALID: SENTINEL, DELIMITED, INVALID_DELIMITER
warning: failed parsing Int64 on row=30001, col=3, error=INVALID: SENTINEL, DELIMITED, INVALID_DELIMITER
File Size of /tmp/wdfname.csv: 1662908
```

**Comment by quinnj** [comment]
So there are a few different things going on here:
* Your `n` and `i` columns end up as `String` columns, but the last row has values of `"missing"` (i.e. _string_ values) instead of `missing` the missing value, because `string(missing) == "missing"`
* So when you write out a csv file w/ that DataFrame, your final csv row looks like:
```
29999,32998.9,29999,173.20219398148512,10.308919326755392
30000,33000.0,30000,173.20508075688772,10.308952660644293
,missing,missing,,
```
* Then when you read the file back in with `CSV.read`, it looks like it's not using the last row for type inference, so it infers column `n` as Float64 and column `i` as Int64, but when it tries to parse the string value `"missing"` it fails.

So technically, CSV.jl isn't doing anything wrong here. However, we should improve the type inference algorithm to make sure it always uses a chunk of rows at the end of a file, since it's not uncommon to have slightly different values at the end of a file. With that, `CSV.read` would correctly infer that columns `n` and `i` are String columns.

**Comment by iwelch** [comment]
I think the default writer should always quote strings, when the type is a Union with Missing.  This way, the reader can disambiguate missing from "missing".

an alternative for strings would be to write missing the same as ""?  it would erase the distinction between empty and missing.  it would mean that all missing strings become empty strings.  but then again, you cannot distinguish between the string missing and the value missing now, either.

but whatever is decided, I would posit that a `csv.write` should always be rereadable with a `csv.read`.  ideally, the basic type would always be preserved, too (int, float, or string; ideally with union to missing).

hope this helps.

**Comment by nalimilan** [comment]
There's really no way to guarantee that types will be preserved in all cases. That's just an inherent flaw of the CSV format. We can't even guarantee that type detection will work on files that were written by CSV.jl, since a single `missing` value in the middle of the fail can escape detection, except if we used all rows, which is terribly slow. Beyond what @quinnj proposed, the two ways to mitigate that are:
- support widening the element type when encountering a value which doesn't fit the type
- support (at least from `CSV.read`) starting parsing from scratch with new types in the most difficult cases (https://github.com/JuliaData/CSV.jl/pull/203).
