### ISSUE TITLE
Files with initial whitespace read into oddly shaped tables with ignorerepeated

### ISSUE THREAD

**Issue by c42f** [JuliaData/CSV.jl#326]
Here's an example where I get an oddly shaped table from ignorerepeated. Note the initial whitespace before the first values on each line; removing the initial whitespace makes the problem go away.

```julia
julia> data = """
         A  B
         1  2
         11 22
       """
"  A  B\n  1  2\n  11 22\n"

julia> CSV.read(IOBuffer(data), ignorerepeated=true, delim=' ')
2×3 DataFrame
│ Row │ Column1 │ A      │ B       │
│     │ Int64⍰  │ Int64⍰ │ Int64⍰  │
├─────┼─────────┼────────┼─────────┤
│ 1   │ 1       │ 2      │ missing │
│ 2   │ missing │ 11     │ 22      │
```

**Comment by quinnj** [comment]
Alright, I think I've got this figured out: the solution is to treat newline characters special (upon request) in the Parsers.Delimited layer. We were already kind of treating them special on the CSV-side because we're interested when parsing terminates due to a delimiter vs. newline in some scenarios; it's also pretty straightforward and common to want to handle newline characters like this, so we might as well just bake it in to the Delimited layer. This simplifies some of the CSV file detection code and ensure the original problematic example in this issue parses as expected.
Once the Parsers.jl change is merged, I'll tag a release and put the CSV side of the change up.
```julia
julia> f = CSV.File(IOBuffer(data), delim=" ", ignorerepeated=true) |> DataFrame
2×3 DataFrame
│ Row │ Column1 │ A      │ B      │
│     │ Missing │ Int64⍰ │ Int64⍰ │
├─────┼─────────┼────────┼────────┤
│ 1   │ missing │ 1      │ 2      │
│ 2   │ missing │ 11     │ 22     │
```

**Comment by quinnj** [comment]
Test added in https://github.com/JuliaData/CSV.jl/pull/336

**Comment by c42f** [comment]
Nice, works for me in latest master :+1:
