### ISSUE TITLE
CSV.File could have more flexible interface

### ISSUE THREAD

**Issue by andyferris** [JuliaData/CSV.jl#348]
I'm wondering if `CSV.File` could have a more flexible interface.

It seems to currently support a minimal *Tables.jl* row-table interface. You can `iterate` things you can call `getproperty` on.

However, it seems to me that the `positions` field makes it random access and IIUC maybe it could easily become a `AbstractVector{NamedTuple{names, ...}}`?

It also seems possible (perhaps not ideal for performance, of course) to extract columns from a CSV.File as a lazy vector view. So it could simultaneously be a column-accessible table that supports `getproperty` for column access.

My goal here is to allow manipulation of a `CSV.File` in an extremely analogous way to a `DataFrame`, `Vector{NamedTuple}` or `TypedTables.Table`. Would this be of interest?

**Comment by quinnj** [comment]
In general, yes, I like the ideas here. My only main concern is that users may get tripped up if they treat it purely like a DataFrame and expect repeat access to be fast each time. The laziness can really only go so far before you actually have to start parsing values, which is the most expensive part of csv reading. I've thought we could maybe get around this by doing some sort of caching in the background; this could be useful anyway because for small files, we effectively parse the entire file twice: once for type inference, and once for the actual values. Now, in some cases that's inevitable, because during type inference we might parse an entire column as Ints, but then the last value of the column is a float, so the _actual_ parsing later on will parse them all as floats, but in general, when type inference is easy and predictable, it would be more efficient to cache the values we parse the first time for more efficient access later.

Note that in the `tables.jl` source file, we already have a `Columns` type where small csv files are fully materialized as a property-accessible object.

**Comment by andyferris** [comment]
Yes, we'd definitely want to make sure users are aware that it is a slower container using on-disk storage. I imagine most people prefer to use `CSV.read` rather than `CSV.File` anyway.

(By the way, `CSV.read` seams to be missing from the online documentation).

**Comment by quinnj** [comment]
Since #395, this has become more feasible, due to the fact that we're only parsing things once upon initial `CSV.File` creation. A question I have in my mind, however, is if we should make `CSV.File <: AbstractVector{NamedTuple{names, ...}}` or if it should be `CSV.File <: AbstractVector{CSV.Row}}`, since that's what it currently iterates. Would there be any advantage anywhere to making it iterate NamedTuples directly + subtyping?

**Comment by andyferris** [comment]
If the `Row` type has a similar interface to `NamedTuple` (i.e. `getproperty`) than this seems fine to me?

I think requiring all table rows to be `NamedTuple`s is a bit too strict.

**Comment by andyferris** [comment]
I guess you might want to consider what `collect(csvfile)` does. It might be convenient to give a nice in-memory (row-based or column-based) container. I would expect `collect(::AbstractVector)` to conserve the element type (and `===`). Food for thought.

**Comment by quinnj** [comment]
Implemented in https://github.com/JuliaData/CSV.jl/pull/525
