### ISSUE TITLE
Package should belongs to JuliaIO

### ISSUE THREAD

**Issue by o314** [JuliaData/CSV.jl#370]
Hello JuliaData,

I'm fighting with entropy in the Julia world those days. It's becoming very,
very hard to know where to grasp a recommended / authoritative package among
Julia ones, even in 2019.

Doesn't this package would be better hosted at
[JuliaIO](http://github.com/JuliaIO) so anyone concerned would
find it easily ?

Thanks

**Comment by nalimilan** [comment]
I'm not sure the goal is to have all packages which read files under the JuliaIO organization. Organizations are about who contributes to a package, not necessarily to help finding packages. Use JuliaObserver for that.

**Comment by o314** [comment]
Hello. Thanks for the quick answer.

It's the third answer i got to same question i have posted over JuliaData, JuliaBio.
Answers vary between no or don't know.

I'm bit disconcerted by these kind of response. So what's the purpose of JuliaIO, JuliaData, JuliaBio ?
All of them gather free open source software with clearly stated topical orientation behind one language and around one discipline. Are they so much barrier in the opensource world of julia to gain access to get permission to commit to JuliaIO?

I'm sorry to say this kind of answer appeal more to a personal centric approach than a scientific community one.

It's not only a matter of search engine but of scientific review. And gathering contributions too.
If everything remains scattered this work will not be done at all.
And that's not a constructive attitude from science workers.

I understand this will not be a simple/quick move to get there.
But closing shortly the question is a no way too.

Nothing personal there of course

**Comment by o314** [comment]
That's what i call pontificating

**Comment by o314** [comment]
I think you try to represent the Julia world but you aren't, you're just a french parisian dealing with american to be  both fascinated and arrogant. 
You take anything personnally and affectively, you're not a scientist that's intented.

**Comment by quinnj** [comment]
@o314, please try to keep the conversation focused on technical subjects instead of personally attacking contributors. We value the feedback and it's not the first time it's been brought up to have CSV.jl be moved to JuliaIO. The reality is that none of the current main contributors, who are non-paid, seem to have much of an appetite for moving the package. As is usually the case in open-source development, if this issue matters so much to someone, they should usually take the initiative in doing the work, which in this case would involve figuring out necessary changes to METADATA, implications of repo transfer, how moving would affect documentation links, making sure main contributors would still have access after a move, and finally, making persuasive arguments to repository owners that the move would be worth it.
