### ISSUE TITLE
low level API: how to skip field, test for EOL, EOF

### ISSUE THREAD

**Issue by tpapp** [JuliaData/CSV.jl#45]
I am processing a CSV file by rows. The file is huge, only certain rows are kept according to a filter function, and constructing a `DataFrame` would be prohibitively expensive and also unnecessary. So I would prefer to read into a tuple/vector, from which I would construct a composite type. Some fields need to be skipped.

Currently using something like this:

``` julia
"Read a line of given `types` from `source`. A `Void` type skips the field."
function parseline(source::CSV.Source, types; row=0)
    values = []
    for (col,T) in enumerate(types)
        if T == Void
            # FIXME: could we just skip?
            CSV.parsefield(source, Nullable{String}, row, col)
        else
            push!(values, CSV.parsefield(source, T, row, col))
        end
    end
    # FIXME: test for end of line, raise error if not reached
    values
end
```

Then I would so something like (pseudocode)

``` julia
a = []
while !eof(source)
    v = MyType(parseline(source, (Int, Nullable{Date}, Void, Int, Date, Void))...)
    if keep_this_row(v)
        push!(a, v)
    end
end
```

Questions:
1. does `eof(s::CSV.Source)=eof(s.io)` make sense or should I use something else?
2. how to check for the end of the line after `parsefield`?
3. can I skip fields without parsing?

Or should I just use `readsplitline` and post-process that? But that way I can't make use of the missing value framework of `CSV`.

**Comment by quinnj** [comment]
To test if a `CSV.Source` is done, I would use
```julia
Data.isdone(s, row, col)
```
but otherwise, `eof(s.io)` should work fine too.

2. There's an internal `CSV.STATE` variable of type `Ref{CSV.ParsingState}`. `CSV.ParsingState` is an enum with values
```julia
@enum ParsingState None Delimiter EOF Newline
```
Basically, each call to `CSV.parsefield` implicitly sets this `CSV.STATE` variable with the state of parsing when the parsing was finished:
* `None`: the default state
* `Delimiter`: parsing encountered a delimiter character which ended the `CSV.parsefield` function
* `EOF`: parsing encountered the EOF
* `Newline`: parsing encountered a newline which caused parsing to stop

3. Currently there is no way to "skip" a field, though I have some notes jotted down somewhere with some considerations around doing something like this. I'll try to dig them up and post them here and maybe see how much work it would take to get it working. For now, though, what you're doing is best practice (just parse a string and continue on).

**Comment by tpapp** [comment]
Thanks, this works fine. Could you consider adding API functions `eof` and `eol`, ideally with a `CSV.Source` as their argument? (I am assuming that eventually the state will be migrated into `CSV.Source` to avoid globals, but I could be mistaken as I did not study the source deeply).

**Comment by quinnj** [comment]
On current master, you can now do `CSV.File(file; kwargs...)` which returns a lazy-materializing row-iterator. You could accomplish the original goal by doing something like:
```julia
struct CustomType
    a::Int
    b::Float64
    c::String
end

customtypes = CustomType[]

for row in CSV.File(file; kwargs...)
    if should_keep(row.a)
        push!(customtypes, CustomType(row.a, row.b, row.c)
    end
end
```
In this case, only the `a`, `b`, and `c` column values will actually be parsed from the csv file.
