### ISSUE TITLE
Parsing UUIDs

### ISSUE THREAD

**Issue by yakir12** [JuliaData/CSV.jl#453]
Consider this table where the element type of the first column is `UUID`:
```julia
using UUIDs, CSV
[(key = uuid1(), x = i) for i in 1:3] |> CSV.write("tmp.csv")
```
I'm not sure why `CSV,jl` doesn't parse it as such (the element type of the `key` column is `String`):
```julia
julia> CSV.File("tmp.csv", types = [UUID, Int])
CSV.File("tmp.csv"):
Size: 3 x 2
Tables.Schema:
 :key  String
 :x    Int64 
```

**Comment by quinnj** [comment]
Hi @yakir12, currently CSV.jl doesn't support custom parsing at all (though admittedly it's a bit confusing because it allows you to pass `UUID` in as a type, I can fix that). A better way to get what you're going for here is to use `Tables.transform`, like:
```julia
df = CSV.File("tmp.csv") |> Tables.transform(key=x->UUID(x)) |> DataFrame
```
So currently, parsing is only able to support direct parsing to a few, select basic types: `Int64`, `Float64`, `String`, `Date`, `DateTime`.

**Comment by derekmahar** [comment]
> A better way to get what you're going for here is to use `Tables.transform`, like:
> 
> ```julia
> df = CSV.File("tmp.csv") |> Tables.transform(key=x->UUID(x)) |> DataFrame
> ```
@quinnj, where may I find `Tables.transform`?

**Comment by yakir12** [comment]
It got moved to [TableOperations.jl](https://github.com/JuliaData/TableOperations.jl), together with a bunch of other stuff.

**Comment by quinnj** [comment]
Note that when Julia 1.6 is released, it will include [this commit(https://github.com/JuliaLang/julia/commit/a99a87ca59e4dc5b70b9c10af33511be84aaa37e), which means that doing: `CSV.File(file; types=Dict(1=>UUID))` will just work. Until then, you can add a definition like:
```julia
if !applicable(parse, UUID, "")
    Base.parse(::Type{UUID}, str::String) = UUID(str)
end
```
and it will then work
