### ISSUE TITLE
Slow first run loading a tiny csv file

### ISSUE THREAD

**Issue by xgdgsc** [JuliaData/CSV.jl#464]
![image](https://user-images.githubusercontent.com/1189869/59994205-9bc97a00-9685-11e9-97ef-d7f2ee2e45d4.png)
When first run CSV.read to load a tiny csv file (less than 20 lines) into a dataframe, it is unbelievably slow. And allocations seems too much. Afterwards it only takes 0.0001 second to load other similar files.

**Comment by nalimilan** [comment]
Unfortunately that's expected due to compilation of functions. Hopefully at some point it will be possible to do this during package precompilation.

**Comment by quinnj** [comment]
Yes, this is more a function of the language itself rather than something specific to CSV.jl. There are probably some very small improvements we could make by rearranging functions a bit and doing some precompile, but honestly, those efforts have never paid off very much in my experience. I'll take a quick look though and see if there is any low-hanging fruit.
