### ISSUE TITLE
Scientific notation write issue in v0.5

### ISSUE THREAD

**Issue by chris-german** [JuliaData/CSV.jl#480]
I've noticed when writing to CSV files in 0.5, it changes numbers and no longer puts them in scientific notation.

In the code below, the issue is reproduced.

`1.9263083035570026e-11` is displayed as `1.9263083035570026e-11`, but when looking at the written file, it is written as `19263083035570026e-27`. This makes written files a bit more difficult to scan through. 

```
using DataFrames, CSV

y = collect(1.0:4.0)
x = [1.0, 0.0, 1.9263083035570026e-11, 0.5]
df = DataFrame(y = y, x = x)

CSV.write("test.csv", df)
```

**Comment by quinnj** [comment]
Thanks for reporting @chris-german; this changed because we're trying to use a lower-level float printing algorithm to customize the decimal point we print (`','` for european locales, for example).

Luckily, I [recently worked](https://github.com/JuliaLang/julia/pull/32799) on porting/writing an entirely new (and faster!) float printing algorithm to Julia, and I'm planning on completely re-writing the `CSV.write` machinery under the hood to be ***much*** much faster. So sorry for the delay in responding here, and I'm sorry I don't have an immediate solution, but it's coming soon.

**Comment by quinnj** [comment]
This was fixed in the most recent release
