### ISSUE TITLE
reading a big dataset

### ISSUE THREAD

**Issue by udion** [JuliaData/CSV.jl#51]
I'm trying to read a big data set using CSV.read() but it is very slow for my purpose,  the dataset has 1 billion rows and 19 columns, after reading the conversions are made to extract data type from the Nullable type, any suggestions  on how to read it faster? Any method to perform parallel  reading?

**Comment by quinnj** [comment]
Is there a way you can share the dataset? Even if just privately? Happy to try and take a look profiling on my side and try to post what seems to help.

**Comment by udion** [comment]
[https://s3.amazonaws.com/nyc-tlc/trip+data/yellow_tripdata_2015-01.csv](url)

Try this one, I am also currently working on this one, although this is just one months data, there are 11 more such files and that only comprises the data for 2015. But try this one first.

**Comment by Unoqualsiasi** [comment]
Sure i sent you an invitation on a DropBox folder....the file is inside that folder.

Thanks!

**Comment by quinnj** [comment]
I can shave 20% off the read time by doing `@time df = CSV.read("issue51.csv"; types=Dict(2=>WeakRefString{UInt8}, 3=>WeakRefString{UInt8}))`, i.e. specifying the 2nd and 3rd columns should be strings instead of DateTime. This should be fixed in 0.6, however, since DateTime parsing has gotten much faster. I'm trying to get CSV working on 0.6 at the moment, or I would check right now.

**Comment by quinnj** [comment]
On current master, I can read the yellow_tripdata file in about 14s. By comparison, TextParse.jl takes about 20s, while pandas takes around 40s.
