### ISSUE TITLE
"allowmissing is a deprecated keyword argument" - how should I change my code?

### ISSUE THREAD

**Issue by crbinz** [JuliaData/CSV.jl#514]
In my code, I use `CSV.read(..., allowmissing = :all)`. How should I change my code to keep that same functionality?

**Comment by quinnj** [comment]
Previously, `allowmissing = :all` defaulted each column to be `Union{T, Missing}` for whatever `T` column type was inferred in 10,000 sampled rows from the file. CSV.jl now doesn't rely on a random sample, but reads the entire file to determine column types, so there's no need to eagerly promote a column to `Union{T, Missing}` because it will get promoted automatically if a missing values are actually found for that column in the file.

Are you wanting to have `Union{T, Missing}` typed columns, even if there aren't missing values found? I think DataFrames might have some functionality for "promoting" a `T` column to `Union{T, Missing}`; @nalimilan? @bkamins?

**Comment by bkamins** [comment]
use `allowmissing` to create a new `DataFrame` or `allowmissing!` to change an existing `DataFrame`.

**Comment by crbinz** [comment]
Thanks, this answers my question.

**Comment by aminya** [comment]
Shouldn't the warning message give more information? I was getting the same warning, but no clue how to fix this.

**Comment by nalimilan** [comment]
Why not, but it's not really easy to suggest a replacement. In most cases the argument can just be dropped. In others, an additional step can be performed separately: for `:all`, one can call `allowmissing!` on the resulting data frame; for `:none`, one can call `disallowmissing!` on it, which will either be a no-op if there are no missing values, or throw an error if there are (other solutions are possible).
