### ISSUE TITLE
Non-deterministic parsing of missingstring

### ISSUE THREAD

**Issue by altre** [JuliaData/CSV.jl#533]
In repeated runs, in some cases, the missingstring is parsed as missing in other cases it is not.
See the following sample using [testfile.txt](https://github.com/JuliaData/CSV.jl/files/3862868/testfile.txt):

```
using CSV

input = "testfile.txt"

inp = CSV.Rows(input; 
		header=[:a, :b, :c, :d , :e , :f], 
		delim='\002', missingstring="NULL");
function collectall(inp)
    set = Set()
    for (i,r) in enumerate(inp)
        push!.(Ref(set), r)
    end
    set
end
s1 = nothing
s2 = nothing
for i in 1:100
    global s1 = collectall(inp)
    global s2 = collectall(inp)
    @assert s1 == s2 string(i)
end
setdiff(s1, s2)
setdiff(s2, s1)
```

Output:

```
julia> for i in 1:100
           global s1 = collectall(inp)
           global s2 = collectall(inp)
           @assert s1 == s2 string(i)
       end
ERROR: AssertionError: 2
Stacktrace:
 [1] top-level scope at ./REPL[335]:4

julia> setdiff(s1, s2)
Set(Any[missing])

julia> setdiff(s2, s1)
Set(Any[])
```

And sometimes Set(Any["NULL"]), too.

**Comment by quinnj** [comment]
Thanks for the report @altre and sorry for the surprise here; this is due to how the underlying Parsers.jl library was using the sentinel values being passed. It wasn't keeping a reference to the sentinel strings (assuming they'd always be in scope), but when you pass it as an argument, it's easy for that to not be the case. Anyway, fix is up here: https://github.com/JuliaData/Parsers.jl/pull/42
