### ISSUE TITLE
Using CSV.read on file handle breaks future reads

### ISSUE THREAD

**Issue by fergu** [JuliaData/CSV.jl#549]
I want to read a CSV file which has several chunks of distinct data. The file is formatted something like...

```
"ZONE 1", I=100, J=200
(100*200 rows x 4 cols of data follow)
...
"ZONE 2", I=150, J=220
(150*220 rows x 4 cols of data follow)
...
```

The values of I and J I put here are arbitrary, and I do not know them ahead of time. What I want to do is open the data file using `open(filename)`, read the first line and parse it to get I and J, do a `CSV.read(...,limit=I*J)` to get the that zone of data, do various reshaping operations on each column, then read the line following the I*J rows to get the information about the next zone, and so on until I hit the end of the file.

I've got all the parsing/get I and J/etc figured out. The problem I'm hitting is when trying to read the data. What I'm observing is that if I do something like

```
open(fpath) do file
    for line in eachline(file)
        # Determine I and J here
        # do stuff with readline(file) and regex
        arr::DataFrame = CSV.read(file,header=false,limit=I*J)
        # Do stuff with the result
    end
end
```

The expected behavior is that the next iteration of `line` should contain the next row, but instead the loop exits as if I've hit EOF. I've tried calling `readline(file)` immediately after the call to `CSV.read` and get a blank/empty line as well.

Removing the call to `CSV.read()` and replacing it with something like
```
for i in range(1,stop=I*J)
    readline(file)
end
```
works as expected.

I have confirmed that the first use of `CSV.read` returns the correct data, and that the next line in the actual file is not a blank line. I've also tried doing a loop with some arbitrary number of `readline()` calls to see if that helps, which it does not.

I am still very new to Julia, so it's possible I'm doing something stupid. Is this a bug, or am I just doing it wrong?

**Comment by quinnj** [comment]
@kjfergu, thanks for opening an issue and yes, you're correct in your findings; currently, if you pass an `IO` argument to `CSV.read`/`CSV.File`, the entire IO is consumed as a single table. There currently isn't a way to have it "stop" at a certain line, since it just consumes until `eof`.

This has come up a few times now and I have some ideas on how to support this with `CSV.Rows`, which is an iterator-based approach to consuming files. In the mean time, you would have to do something like:
* reading the initial line w/ I/J args,
* Make an `IOBuffer` that you will write `I` # of lines into by `readline`ing them
* Pass that IOBuffer to `CSV.read`/`CSV.File`
