### ISSUE TITLE
Why transpose with datarow not output correct?

### ISSUE THREAD

**Issue by dlintw** [JuliaData/CSV.jl#560]
```
julia> s="col1,col2,col3
       1,2,3
       4,5,6
       7,8,9
       10,11,12
       13,14,15
       16,17,18
       19,20,21"
"col1,col2,col3\n1,2,3\n4,5,6\n7,8,9\n10,11,12\n13,14,15\n16,17,18\n19,20,21"

julia> CSV.File(IOBuffer(s); datarow=4)
5-element CSV.File{false}:
 [7, 8, 9]
 [10, 11, 12]
 [13, 14, 15]
 [16, 17, 18]
 [19, 20, 21]

julia> CSV.File(IOBuffer(s), transpose=true)
2-element CSV.File{false}:
 ["col2", 2, 5, 8, 11, 14, 17, 20]
 ["col3", 3, 6, 9, 12, 15, 18, 21]

julia> CSV.File(IOBuffer(s); datarow=4, transpose=true)
2-element CSV.File{false}:
 [2, 8, 14, 20]
 [3, 9, 15, 21]

```

**Comment by quinnj** [comment]
I'm not sure what exactly you're intending for your data here; the data itself only has 3 columns, so specifying that `datarow=4` should probably throw an error, since it's greater than the # of columns detected. That is, `datarow` refers to the _transposed_ row at which you want to start reading data. Does that make sense? Are you dealing w/ a specific file you could share where it's confusing or would be helpful to be treated differently?

**Comment by dlintw** [comment]
I just found the transpose may put warning or error when it can not do the 'transpose'.  Or the result is strange.

**Comment by quinnj** [comment]
Well, you can always _try_ to transpose a file; it's really up to the user if it's "strange" or not. Let me know if there's something more specific you think we could warn/error on. Happy to discuss more.
