### ISSUE TITLE
Warning: Parsed expected 10 columns

### ISSUE THREAD

**Issue by ranjanan** [JuliaData/CSV.jl#583]
Hi Jacob, 

I have a file (attached here) that `readdlm` does not seem to have trouble with:
```julia
julia> a = readdlm("../1m/cellmap.asc", skipstart = 6)
1000×1000 Array{Float64,2}:
.
.
.
``` 
But when I run `CSV.read` on this, I get the following warning. I'm not sure why this pops up and only reads 10 columns: 

```julia
julia> @time b = Array(CSV.read("../1m/cellmap.asc", skipto=7, type = Float64, delim = " ", threaded = false));
thread = 1 warning: parsed expected 10 columns, but didn't reach end of line on data row: 1. Ignoring any extra columns on this row
thread = 1 warning: parsed expected 10 columns, but didn't reach end of line on data row: 2. Ignoring any extra columns on this row
thread = 1 warning: parsed expected 10 columns, but didn't reach end of line on data row: 3. Ignoring any extra columns on this row
.
.
.
```

Is there obvious that I'm missing? Thank you for your time. 

(Note that I gzipped the file so I can upload to GitHub)

[cellmap.asc.gz](https://github.com/JuliaData/CSV.jl/files/4347350/cellmap.asc.gz)

**Comment by quinnj** [comment]
You need to pass `header=false`; otherwise, it's trying detect the # of columns from the 1st row. So what works for me on that file is `f = CSV.File(file; header=false, datarow=7, type=Float64)`. Note however that there's an extra `' '` space at the end of each row, which is the delimiter, so it parses an extra "missing" column, so you end up with 1001 columns. That's pretty easy to ignore using `TableOperations.select` or using a DataFrame operation, but just wanted to point it out.

We could perhaps find a way to allow you to ignore trailing `missing` columns for cases like this.
