### ISSUE TITLE
Reading to a rowtable 20x slower than to a columntable

### ISSUE THREAD

**Issue by robsmith11** [JuliaData/CSV.jl#614]
If anything, I would expect reading to a rowtable to be slightly faster because every tuple can be read in order.

```
julia> CSV.write("/tmp/df.csv", DataFrame(a=1:10^6, b=randn(10^6)))
"/tmp/df.csv"

julia> @time columntable(CSV.File("/tmp/df.csv"));
  0.105678 seconds (120 allocations: 40.477 MiB)

julia> @time columntable(CSV.File("/tmp/df.csv"));
  0.104145 seconds (120 allocations: 40.477 MiB)

julia> @time rowtable(CSV.File("/tmp/df.csv"));
  2.367711 seconds (11.00 M allocations: 849.170 MiB, 3.07% gc time)

julia> @time rowtable(CSV.File("/tmp/df.csv"));
  2.351094 seconds (11.00 M allocations: 849.170 MiB, 1.75% gc time)
```

**Comment by quinnj** [comment]
Thanks for filing an issue; I'll try to walk through some thoughts:

* `CSV.File` indeed parses the input file row-by-row, but constructs _column vectors_ as it parses; this is to accommodate the most common use-case of doing `DataFrame!(CSV.File(...))`; it's also just common to want column vectors to operate on for modeling, statistics, etc.
* That said, `CSV.File` iterates rows itself, so you can get the "rows" of a file by doing: `collect(CSV.File(...))`, and indeed this is much faster than calling `rowtable`
```julia
julia> @time CSV.File("/tmp/df.csv");
  0.031677 seconds (465 allocations: 20.368 MiB)

julia> @time collect(CSV.File("/tmp/df.csv"));
  0.043561 seconds (465 allocations: 50.886 MiB)
``` 
Each "row" when iterating a `CSV.File` is a `CSV.Row` object that acts just like a `NamedTuple` and can be used as such (e.g. you can get the value of `col1` by doing `row.col1`)
* `rowtable`, on the other hand, is specifically defined as a `Vector{<:NamedTuple}`, and so in the case of `rowtable(CSV.File(...))`, each `CSV.Row` is basically materialized as a `NamedTuple`. If you happen to need `NamedTuple`s specifically, then so be it, but note that there's an inherent cost to convert a `CSV.Row` (which is just a "view" object into the `CSV.File`) and a fully materialized `NamedTuple`. I will note, that for me, on CSV#master, I only see about a 4x slowdown between `columntable` and `rowtable`:
```julia
julia> @time columntable(CSV.File("/tmp/df.csv"));
  0.029206 seconds (468 allocations: 20.368 MiB)

julia> @time rowtable(CSV.File("/tmp/df.csv"));
  0.132348 seconds (4.00 M allocations: 96.639 MiB, 8.60% gc time)
```
The difference between your post might be due to general performance improvements on CSV#master (which have been quite a few).

Also note that CSV.jl provides a `CSV.Rows` type specifically for the case of wanting a low-memory-footprint, performant alternative to `collect(CSV.File(...))`. It takes most of the same arguments as `CSV.File`, but returns a row iterator.

```julia
julia> function ff(rows)
       i = 0
       for row in rows
           i += 1
       end
       return i
       end
ff (generic function with 1 method)

julia> @time ff(CSV.Rows("/tmp/df.csv"; reusebuffer=true))
  0.070385 seconds (77 allocations: 10.625 KiB)
1000000
```
In this case, we're passing `reusebuffer=true`, which means each iterated row is only valid when it is currently iterated (i.e. can't call `collect(CSV.Rows(...; reusebuffer=true))`). But we get similar speed to `collect(CSV.File(...))` with a very small fraction of the memory footprint.

Hope all that helps!
