### ISSUE TITLE
thoughts on the data structure choices

### ISSUE THREAD

**Issue by JeffreySarnoff** [JuliaData/CSV.jl#637]
Sentinel Values seems more facile and flexible. Certainly for Floats.
The token `missing` should be allowed in any event (maybe a keyword in CSV.read to toggle type with Missing, scan_for_missing `missing=true`).

#### NaNs for Sentinel Values
(a) zero payloads with the signbit set
- NaN16: reinterpret(Float16, 0xfe00)
- NaN32: reinterpret(Float32, 0xffc0_0000)
- NaN64: reinterpret(Float64, 0xfff8_0000_0000_0000)

(b) improbable payloads (using the word "facade")
- NaN16: reinterpret(Float16, 0xffac) [signed payload is -428]
- NaN32: reinterpret(Float32, 0xfffacade) [signed payload is -3853022]
- NaN64: reinterpret(Float64, 0xffffacade0facade) [signed payload is -2160187640826590]

#### Sentinel Int Values
I used to use `typemin(T)` as it is squirrely anyway.  Other values seem more clashable, inadvertently.  

#### String columns
Is it feasable to PR WeakRefStrings to make the inconsistencies go away?

**Comment by quinnj** [comment]
Thanks for the suggestions @JeffreySarnoff; the implementation now lives [here](https://github.com/JuliaData/SentinelArrays.jl/blob/98bfc4462de68c3b9aeae86fda981f4d8c385a5d/src/SentinelArrays.jl#L75-L76). We ended up going with `reinterpret(Float64, 0xffffffffffff)` because it has the nice property of being able to `memset` the array after initialization. For `String` columns, we're just using `#undef`, which works pretty well since it cant' mean anything else :P. 

Small int types are really the only pain because of the danger of collision. (large int types will probably be so rare that it's not as big a deal).
