### ISSUE TITLE
weird typemap behavior (bug?)

### ISSUE THREAD

**Issue by kragol** [JuliaData/CSV.jl#680]
The `typemap` option to `CSV.File` produces incorrect types when mapping Integer types (I haven't really tested other types though). Basically, all `Int` columns are converted to `Float64` whatever the typemap indicates as a target type.

MWE:
file `test.csv`:
```
"a","b","c"
1,"a",12
1,"a",12
```

```julia
julia> CSV.File("test.csv"),typemap=Dict(Int64=>Int32))
2-element CSV.File{false}:
 CSV.Row: (a = 1.0, b = "a", c = 12.0)
 CSV.Row: (a = 1.0, b = "a", c = 12.0)
```
Here, the values of `a` and `c` are converted to `Float64` instead of `Int32` as requested.

```
julia 1.4.2
CSV 0.7.2
```

**Comment by quinnj** [comment]
Hmmm, yes, this is a bug. It turns out `typemap` wasn't adjusted property for our new "custom types" life we enjoy now. It still assumes you will only map types between the "standard" types (Int64, Float64, Bool, Date, DateTime, Time, Bool). I'll start noodling on how to make sure we're correct here.
