### ISSUE TITLE
Performance regression?

### ISSUE THREAD

**Issue by xiaodaigh** [JuliaData/CSV.jl#695]
Reading the [Fannie Mae Performance 2003Q3](https://docs.rapids.ai/datasets/mortgage-data) file is now taking 2~3 mins. Thats' about 2-3x slower than one month ago.

Both `CSV.File()` and `CSV.read()` are slower and taking up all 64G of the RAM on my computer.

**Comment by quinnj** [comment]
Yeah, I think we regressed a bit with some of the heuristic tuning I've done; can you try on [this PR](https://github.com/JuliaData/CSV.jl/pull/688) and see how that works for you? I'm currently sketching out the last parts of performance tuning I want to iron out before 1.0 release, and most of the work is going into that PR.

**Comment by xiaodaigh** [comment]
OK, yeah. That is MUCH faster (2-3x) and uses less RAM.

**Comment by stej** [comment]
Any idea when this will be released? I face some perf problems, so I'd like to give it a try.

**Comment by quinnj** [comment]
@stej , the fix for this issue has been released in the latest version (v0.7.7). Can you ensure you're on the latest version? If you're still seeing performance issues, can you file a new issue and I'll investigate?

**Comment by stej** [comment]
I tried to make a repro so that I can report it. But I've failed so far. 

I have 2GB CSV file, which causes problems during loading - it takes minutes. So to reproduce the behaviour I tried to generate similar file, but even though the structure is the same (4 columns - string, string, int, datetime), it takes about 30sec.

So, I have no repro so far.
