### ISSUE TITLE
default to bom = true in CSV.write?

### ISSUE THREAD

**Issue by kafisatz** [JuliaData/CSV.jl#697]
What is the motivation for defaulting `bom = false` in `CSV.write` ? 

I just noticed, that on Windows, when I write a CSV and open it with Excel (which seems frequent use case), "ä" and similar are not displayed correctly.

**Comment by quinnj** [comment]
I guess that means excel requires a BOM character in order to understand UTF8? When I import a csv, I have the option to choose a "file origin" and can select UTF8 from the list. Maybe that would resolve your issues? Writing the BOM character by default would be breaking and is kind of a legacy technique in the world these days.

**Comment by kafisatz** [comment]
Ah ok. I did not realize this would be breaking. Fine for me.
I was referring to opening by double click. This does not prompt any dialog wrt encoding (or delimiter).
