### ISSUE TITLE
Provide a way to ignore repeated delimiters while parsing

### ISSUE THREAD

**Issue by merl-dev** [JuliaData/CSV.jl#71]
I was trying to load a data file that occasionally has multiple spaces between observations and was surprised to see this for the following contents:
```
a b c d e
1 2  3 4 5
1 2 3  4 5
1  2 3  4 5
```
```
julia> t = CSV.read("Untitled.txt", delim=' ' , header=true)
3×5 DataFrames.DataFrame
│ Row │ a │ b │ c     │ d     │ e     │
├─────┼───┼───┼───────┼───────┼───────┤
│ 1   │ 1 │ 2 │ #NULL │ 3     │ 4     │
│ 2   │ 5 │ 1 │ 2     │ 3     │ #NULL │
│ 3   │ 4 │ 5 │ 1     │ #NULL │ 2     │
```
Any suggestions on how to resolve this?

**Comment by nalimilan** [comment]
I don't think the delimiter is supposed to be repeated. The CSV/TSV format only uses the delimiter once.

That said, an error should be thrown rather than putting the data in the next row.

**Comment by merl-dev** [comment]
I have this problem when opening one of the UCI Machine Learning Repository datasets.  Using DataFrames.jl this doesn't happen, so I thought it might be something CSV should handle.  Perhaps this is a common occurence with this delimiter.

**Comment by nalimilan** [comment]
One of the issues is that in CSV `,,` indicates an empty field (missing value), and even with space-delimited files this isn't an absurd interpretation. Not sure how this works with `readtable`, maybe it has a special case for the space delimiter? What do other software do in that case?

**Comment by merl-dev** [comment]
Ok so while looking at the raw data file I was working with it appears that I am dealing with a data-acquisition system that uses a decimal32 format (14 chars), sampling freq of 50 Hz for 2.56 secs=>128 samples per row. So if line length is 2050 chars, remove the `\r\n' giving 2048/128=16, and since a dec32 is only 14 chars => 2 white space characters between each observation.  

Sooooo.... splitting a line on 2 white space gives an almost perfect parse, as there is an empty item in position one of the resulting vector (and the 2 end of line chars that also need to be removed).

What all of this implies is that in some cases, e.g. DAQ, the fastest parse means the current interface for CSV needs more info than presently offered.  A little bit of Julia magic, and likely using DecFP.jl, and we have a really fast parser for real time DAQ  interface.

**Comment by nalimilan** [comment]
There's still a bug AFAICT: some cells appear in the incorrect row.

**Comment by merl-dev** [comment]
if you have no header OR no type info for each line (both implying line length) then you can imagine  a case with variable length lines and nulls.  So, in my mwe, yes it is a bug because a header is specified, and the bug fix is to make sure that each line is consistent with header or eltypes specified.  All of the parsers that I currently use seem to do this, except the one used by excel and open office where line lengths end up as variable.

**Comment by merl-dev** [comment]
Sorry for closing the issue, and pondering scenarios where line lengths/items are fixed width so there may be sequence of delimiting chars.

**Comment by quinnj** [comment]
We now have the `CSV.validate` function which takes the same arguments as `CSV.read`, but which returns useful error information for improperly formatted csv data. The example above shows
```julia
julia> io = IOBuffer("""a b c d e
       1 2  3 4 5
       1 2 3  4 5
       1  2 3  4 5""")
IOBuffer(data=UInt8[...], readable=true, writable=false, seekable=true, append=false, size=43, maxsize=Inf, ptr=1, mark=-1)

julia> CSV.validate(io; delim=' ')
ERROR: CSV.TooManyColumnsError("row=1, col=5: expected 5 columns then a newline or EOF, but parsing encountered another delimiter: ' '; parsed row: '1 2 null 3 4'")
Stacktrace:
 [1] validate(::CSV.Source{Base.GenericIOBuffer{Array{UInt8,1}},Nulls.Null}) at /Users/jacobquinn/.julia/v0.7/CSV/src/validate.jl:30
 [2] #validate#40(::Bool, ::Dict{Int64,Function}, ::Array{Any,1}, ::Function, ::Base.GenericIOBuffer{Array{UInt8,1}}, ::Type{T} where T) at /Users/jacobquinn/.julia/v0.7/CSV/src/validate.jl:38
 [3] (::getfield(CSV, Symbol("#kw##validate")))(::Array{Any,1}, ::typeof(CSV.validate), ::Base.GenericIOBuffer{Array{UInt8,1}}, ::Type{T} where T) at ./<missing>:0 (repeats 2 times)

```

**Comment by simonbyrne** [comment]
I'm reopening this since it was available in `DataFrames.readtable`, but that has now been deprecated in favour of `CSV.read`. So there should be a way to do this somehow.

**Comment by quinnj** [comment]
What's the request here, ignore repeated delimiters?

**Comment by simonbyrne** [comment]
Yes.

**Comment by gizmaa** [comment]
Please make this something the user can choose. I have data files with double delimiters because there is no value. I'm indifferent to which way is actually default.

**Comment by simonbyrne** [comment]
Agreed, an option would be best.

**Comment by 0kto** [comment]
Hi all,
I would like to make a strong case for such an option:
I was using the DataFrames `readtable()` function extensively in order to read data generated by neutron spectrometers (housed at large scale facilities, so no change in the format can be expected), and you get all kinds of ugly raw data-files. These have TAB delimiters converted to spaces (so number of those changes all the time, even for the same column), several different delimiters, blocks for different kinds of metadata separated by lines like `[DATA]`
The point is that some scientific data comes in a format that is not strictly CSV compliant.

`readtable` was working correctly with those with the option of `ignorepadding::Bool` set to `true`, which "Ignore[s] all whitespace on left and right sides of a field. Defaults to true." (from [Docs of DataFrames v0.10](http://juliadata.github.io/DataFrames.jl/release-0.10/man/io/#Importing-data-from-tabular-data-files-1) ).

**Comment by anowacki** [comment]
I have recently come across this, and would love to see the addition of an option to allow multiple delimiters between fields.

`readtable` has told me to use `CSV.read`, but fields in my files are separated by variable numbers of spaces.  I currently have no other option but to ignore the deprecation and use `readtable` until it disappears, use some (future variant of) `readdlm` and custom code to get things into a `DataFrame`, or preprocess every single file with external utilities by shelling out.

For what it's worth, many decades of scientific data (certainly in my field, geophysics) have been created as plain-text files where each column is aligned to make files human- as well as computer-readable (written with format statements in Fortran, C, etc., and read with C, Fortran, Matlab, `awk`, etc.).  This necessarily entails variable number of spaces being used.  I had ignored the `CSV` package because I have never come across data separated by commas.

**Comment by davidanthoff** [comment]
@anowacki You can use [CSVFiles.jl](https://github.com/davidanthoff/CSVFiles.jl) in the meantime. ``df = DataFrame(load("filename.csv", spacedelim=true))`` should work.

**Comment by anowacki** [comment]
Thanks, @davidanthoff !

**Comment by 0kto** [comment]
Regrettably, CSVFiles.jl is much less powerfull than the original `DataFrames.readtable` or `CSV.read`.
Currently I have a file with several header sections, so I grab the data in the tables using `Base.readlines()`, parse it with
```
data_of_interest = join(join.(split.(file_content[data_start:data_end], " ", keep=false), "," ), "\r" )
```
to replace any empty space with commas, and read a IOBuffer of it
```
dataframe = CSV.read( Base.IOBuffer(data_of_interest) )
```
I hope this helps anyone searching for a solution; however, I kinda expect it to break (again!) in the near future.
I had a look at the source code, but I have no idea where to put anything like the above command, so I can not really make a pull request here :/

**Comment by DarioSarra** [comment]
Not sure if it's the correct issue, but I found that while CSV.read was able to handle strings where there was a newline character (/n) CSVFiles.load interrupt the reading of the raw resulting in less fields than the previous column.

**Comment by anowacki** [comment]
@DarioSarra I think this issue is about reading of files where repeated delimiters between each record may be present, rather than the presence of newlines (`\n`), so I think yours is an orthogonal case to deal with.

**Comment by DarioSarra** [comment]
@anowacki thanks for the clarification

**Comment by quinnj** [comment]
PR up to support this: https://github.com/JuliaData/CSV.jl/pull/254
