### ISSUE TITLE
ability to skip malformed records

### ISSUE THREAD

**Issue by asbisen** [JuliaData/CSV.jl#76]
It would be nice to add ability to be able to handle csv files with malformed records. This could be achieved by either a keyword argument `skip_malformed_with_warn` which will skip the lines that the parser is unable to parse with a warning. Or a keyword `skip_lines` that would be an array to identify the line numbers that should not be read.

**Comment by quinnj** [comment]
This will be fully implemented in #395, where there are two keyword arguments to control behavior: `strict` and `silencewarnings`. By default, `strict=false` and `silencewarnings=false`, so malformed rows will be skipped, but a warning will be printed. You can avoid printing the warnings w/ `silencewarnings=true`, or choose to throw an error on malformed rows via `strict=true`.

**Comment by nalimilan** [comment]
How about using `strict=true` by default BTW? I don't like the idea of dropping data automatically by default.

**Comment by quinnj** [comment]
Personally, I would find it annoying, and in general, my impression is that whenever `CSV.read` can't just "figure out" a file by default, but throws an error, people have a bad experience, think there's something wrong w/ CSV.jl itself. That's why I think it's a good compromise that we have `strict=false`, but `silencewarnings=false` so there is at least noisy warnings to make sure you know something funny happened. I'd be open to having a poll on discourse or something though and if enough people wanted `strict=true` by default, I'd be willing to change.
