### ISSUE TITLE
CSV file not-roundtrippable if a header contains a space

### ISSUE THREAD

**Issue by yurivish** [JuliaData/CSV.jl#799]
It seems that column names with spaces are not escaped on write. This confuses the reading machinery, which inserts extra columns filled with `missing` values to compensate. Minimal reproduction:

```julia
julia> using CSV, DataFrames

julia> CSV.write("test.csv", [(; var"Created Date" = "Today")])
"test.csv"

julia> CSV.read("test.csv", DataFrame)
┌ Warning: thread = 1 warning: only found 1 / 2 columns around data row: 2. Filling remaining columns with `missing`
└ @ CSV ~/.julia/packages/CSV/la2cd/src/file.jl:603
1×2 DataFrame
 Row │ Created  Date
     │ String   Missing
─────┼──────────────────
   1 │ Today    missing
```

This can be fixed by escaping the header values and writing them as quoted strings when needed. The following file with a quoted header (`quoted_header_test.csv`) is read correctly:

```
"Created Date"
Today
```

```julia
julia> CSV.read("quoted_header_test.csv", DataFrame)
1×1 DataFrame
 Row │ Created Date
     │ String
─────┼──────────────
   1 │ Today
```

**Comment by quinnj** [comment]
Alright, let's unpack what's going on here:
* Doing `CSV.write("test.csv", [(; var"Created Date" = "Today")])` notably assumes the default delimiter `','`, so no escaping is required for the column names `Created Date`
* The default `CSV.read` seems to be assuming the delimiter is `' '`, which seems odd to me since the second line doesn't have any spaces; I'm going to look into what's going on here

Do note that you can do `CSV.write(...; quotestrings=true)` to force all strings, including column names, to be quoted when written. You can also specify the delimiter when reading like `CSV.read(file; delim=',')` which also avoids the problem. So it's really a matter of confusing defaults here and I'll look into if there's a tweak we can make on the `CSV.read` side.

**Comment by yurivish** [comment]
Thanks for looking into this, @quinnj. I agree, the default `CSV.read` is odd.

There might be an argument for using quotation marks so that CSVs like this can be read and written with the default `CSV.write` and `CSV.read`.

My original example was actually an "easier" case from the perspective of the heuristic you just described –  the column was titled `"Created Date"`, and each value also had exactly one space, of the form `"12/22/2015 04:50:42"`. If I understand you correctly the `CSV.read` heuristic saw that there was exactly one space in both the header and value, and so decided to use the space as the delimiter.

> Do note that you can do CSV.write(...; quotestrings=true) to force all strings, including column names, to be quoted when written. You can also specify the delimiter when reading like CSV.read(file; delim=',') which also avoids the problem. 

I didn't know about these options, thanks.

**Comment by quinnj** [comment]
Yeah, that's somewhat the danger of relying on automatic delimiter detection in general; it's rule based and not perfect, so it can get confused sometimes. But nonetheless very convenient and right 99% of the time. But yeah, if you're in a more risk-averse setting where you need to avoid issues like this, it's highly recommended to provide the `delim` argument manually to ensure nothing gets confused.

I've opened https://github.com/JuliaData/CSV.jl/pull/801, which should help at least in this very specific case by not considering space characters in the header as valid delimiters, since they're probably rarely meant as such.
