### ISSUE TITLE
Write Bool column ! => read Bool column

### ISSUE THREAD

**Issue by CorySimon** [JuliaData/CSV.jl#81]
I find this behavior erratic that when I write a Boolean column and then load it, it isn't a Boolean column.
```julia
using CSV
using DataFrames

# create toy dataframe with boolean column
df = DataFrame(x=Float64[], y=Bool[])
push!(df, [2.0, true])

# write to file
CSV.write("test.csv", df)

# load again, look at y-column
df2 = CSV.read("test.csv")
df2[:y] # NullableArrays.NullableArray{WeakRefString{UInt8},1}:
```

How can I circumvent this? I tried:
```julia
tinfo = Dict("y" => Bool) # type info
df2 = CSV.read("test.csv", types=tinfo)
```
and got:
```julia
ERROR: CSV.CSVError("error parsing a `Bool` value on column 2, row 1; encountered 't'")
```

**Comment by quinnj** [comment]
Should be fixed on master via 6bebc31e6bce8239779fe89fef58f32798806820. The problem here is that `Bool <: Integer`, so the Integer parser was trying to parse the Bool values and dying. We now have a custom Bool parser, so things get dispatched correctly. I also added support for `truestring` and `falsestring` keyword arguments to support custom Bool parsing.
