### ISSUE TITLE
Allow reading string columns as symbols

### ISSUE THREAD

**Issue by cnowzohour** [JuliaData/CSV.jl#812]
As far as I'm aware string columns are always parsed as Julia strings, and it's not possible to eg specify `types = Dict("myStringColumn" => Symbol)`. A common use case is to have string columns with only a small number of unique values (factors in R). The above limitation then is 1) wasteful and more importantly 2) makes `dropmissing!` incredibly slow. I assume this is because of the non-uniform memory layout of the string column. Doing something like
```
df.myStringColumn = ifelse.(ismissing.(df.myStringColumn), missing, Symbol.(df.myStringColumn))
```
before the dropmissing call fixes it. But it would be nicer to just specify this as an option when reading the file or to support Symbol in the types argument.

**Comment by quinnj** [comment]
By default, if a string column has a low cardinality, it will be parsed as a `PooledVector{String}`, which only allocates one string object per unique string parsed, and the actual column values are int indices into the string pool vector. There is also a reading option to pass `lazystrings=true` to `CSV.File` or `CSV.read` in order to avoid allocating any strings at all until they're actually indexed later on. It can speed up parsing of large files by quite a bit.

So it seems like the core of your issue, if I'm reading correctly is "makes `dropmissing!` incredibly slow"; can you elaborate what you're seeing here and what it's slow in relation to? Sharing a code sample that others can run is most helpful to illustrate that `dropmissing!` is fast in case X, but slow in case Y. That will help the rest of us be able to reproduce the performance issue and be able to diagnose whether it's actually due to large number of string objects, or some unintentional bug, or a datastructure issue or whatever.

**Comment by cnowzohour** [comment]
Interesting, I did not know that's how it's parsed by default. I think the problem in my case was that I explicitly passed the `types` for all columns (incl `String` for string columns), which overrode that behaviour. Thanks for clarifying that.
