### ISSUE TITLE
Default column types when reading CSV files

### ISSUE THREAD

**Issue by bkamins** [JuliaData/CSV.jl#854]
Currently CSV.jl will use custom types to ensure performance in various places (most notably `ChainedVector`s and custom string types).

I think a useful option would be to request that it uses only types provided by Julia Base. I think it would be more newcomer friendly (as they would not have to immediately learn about custom types that are provided for performance reasons).

I am not sure what the syntax should be as the first question to answer is if we want it.
Then assuming we want it if:
* using Julia Base types should be the default (and user should explicitly opt-in for fast types)
* using "fast" types should be the default (and user should explicitly opt-in for standard types)

Any opinions on this?

Rationale:
* corner cases that potentially confuse users (see e.g. https://github.com/JuliaData/SentinelArrays.jl/issues/52; I know that issue can be resolved, but my general comment is that users might need to learn too many new things too soon when they start using the ecosystem)
* ALL JuliaData tutorials using CSV.jl will have to be rewritten (again - of course it is clearly doable; the question is if we want it)

To be clear: I want to have the "fast" types; my only question is if they should be used by default or only on request.
The idea is that most users will use CSV.jl+DataFrames.jl on small data where performance does not really matter as all is fast no matter what types we use.

CC @vjd, @pdeffebach, @nalimilan,  @jkrumbiegel, @oxinabox

**Comment by oxinabox** [comment]
no, I don't think we should change anything here.
I especially don't think we should change the default.
because fast is important.
It's basically a key feature when it comes to CSVs, often they are stupidly large.
To the point that there is a decent chance that something won't work if using slower ways.
Especially, as one of the things the slow ways (using only Base julia types) result in is causing the  GC to be come slow, which is really hard for anyone new to diagnose.
Way harder than an error about e.g. `append!` .
Instead we should just fix all cases when the special types do not work intuitively.

I also don't think we should add a feature to do it.
Such a feature would only be useful for newcommers.
It is fairly trivial to do in post for anyone experienced, and they would be able to apply it far more granularity than we could provide an API for in CSV.jl.
For newcomers, it is vastly more useful if it is default on, since reading the docs and understanding if they should do it is a bit much.

It is within out power to just fix all cases where the special types are not good.

**Comment by bkamins** [comment]
In this case I am x-posting also https://github.com/JuliaStats/GLM.jl/issues/442 for a reference (but this needs fixing in GLM.jl)

**Comment by quinnj** [comment]
Yes, I would agree with the point that "default fast" is very important. At least empirically from issues that are filed and discussions on slack/discourse, users get more upset about things being slow than having custom types returned. I understand the sentiment of keeping things simple though. One of my big plans before the new release soon is to do a very in-depth manual for CSV.jl that should hopefully be very helpful at explaining defaults, why, and how to tweak things to get what you want.

**Comment by quinnj** [comment]
I've updated the docs to mention the various array types that might be returned from `CSV.File`/`CSV.read`.
