### ISSUE TITLE
Using `select` with `CSV.Rows`

### ISSUE THREAD

**Issue by rofinn** [JuliaData/CSV.jl#858]
It's unclear from the documentation whether I'm supposed to be able to call `CSV.Rows` with the `select` keyword. AFAICT, it mostly work, but it seems the `Rows` method returns some extraneous `missing`s.

```julia
julia> first(CSV.File(only(collection.raw_data_inputs); select=[:release_date, :target_start, :target_end, :target_bounds]))
CSV.Row: (release_date = "2017-03-27T20:40:51.000+00:00", target_start = "2017-03-26T00:00:00.000+00:00", target_end = "2017-03-26T01:00:00.000+00:00", target_bounds = 1)

julia> first(CSV.Rows(only(collection.raw_data_inputs); select=[:release_date, :target_start, :target_end, :target_bounds]))
CSV.Row2{Parsers.Options{false, true, true, false, Missing, UInt8, Nothing}, Nothing, Any}: (release_date = "2017-03-27T20:40:51.000+00:00", target_start = "2017-03-26T00:00:00.000+00:00", target_end = "2017-03-26T01:00:00.000+00:00", target_bounds = missing)
```

I get that `Rows` returns `Union{String, Missing`, but I'd expect that `target_bounds` value to be `"1"`.

**Comment by quinnj** [comment]
Looks like select/drop were broken for `CSV.Rows` on `main` branch, but I don't imagine that's the same issue you're seeing here. Is there anyway you can share the file causing the issue here? It may be something more subtle that needs fixing. Alternatively, you could try the same code w/ the code in my PR and see if it's fixed? Sorry for the slow response here, I've been doing a bunch of big internal refactorings on this package lately, and I'm trying to get caught up on issues now.
