### ISSUE TITLE
Error when loading complex NaN's

### ISSUE THREAD

**Issue by DavidWellnitz** [JuliaData/CSV.jl#860]
I have a CSV File which contains complex values and some values are ```NaN + NaN*im```, which throws an error when I try to read it with type fixed to ```ComplexF64```. The underlying problem seems to be that ```parse(ComplexF64, "NaN + NaN*im")``` throws the error: ```ERROR: ArgumentError: cannot parse " NaN*" as Float64```. I tried to "solve" this by setting ```strict=false``` like:
```df = CSV.File(fname, header=header, type=ComplexF64, strict=false) |> DataFrame```
where ```fname``` is the location of my file and ```header``` is the header, but it throws the same error.

Am I using ```strict``` wrong? And is the behavior of ```parse``` intentional?

**Comment by DavidWellnitz** [comment]
Update: Using ```missingstring= "NaN+NaN*im"``` instead of ```strict=false``` works, but it still feels like ```strict=false``` should also work.

**Comment by quinnj** [comment]
Hmmm, yes, an interesting problem. For non-standard types, we currently rely on calling `Base.parse`, but on invalid values, that may throw an error that we're currently not catching. We should probably switch to using `Base.tryparse`, so that `strict=false` works as you mentioned. We could also consider adding parsing support in Parsers.jl for Complex types, which would make parsing them much faster.

**Comment by quinnj** [comment]
Ok, this was fixed in https://github.com/JuliaData/Parsers.jl/pull/86

**Comment by DavidWellnitz** [comment]
Thanks :)
