### ISSUE TITLE
Reading from IO buffer: 0.8 vs. 0.9

### ISSUE THREAD

**Issue by jo-fleck** [JuliaData/CSV.jl#908]
After adding compatibility with CSV 0.9, [this package](https://github.com/jo-fleck/Taxsim.jl) fails a basic CI test.

I just had a quick look and it seems to me that 0.9 parses data from IOBuffers in a slightly different way (I might be wrong).

In 0.8, this command
`df_res = CSV.read(seekstart(io_out), DataFrame; silencewarnings=true)`
returned a data frame with 45 columns.

In 0.9, it returns a data frame with one column. Its title are the 45 concatenated column names (separated by commas).

Is this observation correct? And is there a command which works in both 0.8 and 0.9?

**Comment by quinnj** [comment]
Thanks for the report; any change in behavior here is most likely unintentional. Is there a way you can share an example of the file/input that is passed in the `io_out` IOBuffer?

**Comment by jo-fleck** [comment]
Sure:

```
using CSV, DataFrames
df_upload = DataFrame(year=1980, mstat=2, ltcg=100000, idtl = 12)
io_out = IOBuffer()
run(pipeline(`ssh -T -o ConnectTimeout=10 -o StrictHostKeyChecking=no taxsimssh@taxsimssh.nber.org`, stdin=seekstart(CSV.write(IOBuffer(), df_upload)), stdout=io_out))
df_download = CSV.read(seekstart(io_out), DataFrame; silencewarnings=true)
```

The file is returned from a server and it's possible that some server settings have been changed just when I updated from 0.8 to 0.9 (very unlikely but cannot rule it out).

**Comment by quinnj** [comment]
I'm seeing the same behavior between 0.8.5 and 0.9.3 (reading the whole input as one column); furthermore, I see the same behavior regardless whether the input is an IOBuffer or saved to a file.

The issue as far as I can tell, is the automatic delimiter detection is getting messed up; i.e. it thinks the delimiter should be `' '` (a single space) rather than `','`. A big part of the issue here is we're trying to auto-detect the delimiter for just 2 lines, which can be tricky with our current algorithm, which tries to figure out the delimiter given an even distribution over the lines used for detecting. What that means is that the fewer lines we can use for delimiter detection, the more likely it is we'll incorrectly choose a delimiter.

The other core issue is that the 2nd row has a trailing comma as the last character on the line, which would suggest an "empty" cell (the last cell _should_ be delimited via the newline `'\n'`). That means we have 45 column names in row 1, and 46 cells in row 2, so the delimiter detection algorithm passes over choosing `','` as the delimiter since it's not consistent between rows.

The reason `' '` is chosen is because the first value one the 2nd row is `"0.                            ,"`, i.e. `0.` followed by 28 space characters, then the `','` comma delimiter. Because the 28 spaces are divisible by 2 total rows parsed, it figures the spaces were evenly divided between the 2 rows (another shortcoming of the auto-delimiter detection algorithm) and selects space as the delimiter. Tracking the count of potential delimiters _per row_ would certainly be an improvement that would avoid the issue here, though it's a bit more work.

Another potential improvement is to just require a minimum # of rows in order to do auto-delimiter detection, maybe even just requiring 3 or 4 so it's less likely we run into an issue like this. It's not quite as satisfying, but at least would improve things by a little.

cc: @nickrobinson251 since you might find this an interesting parsing problem.

**Comment by quinnj** [comment]
@jo-fleck , as per the original issue, it seems to me that most likely the data itself changed and the core issues started being hit due to only have 2 rows? Comparing the auto-delimiter detection code paths between 0.8.5 and 0.9.3 doesn't reveal anything significant, so it seems to suggest the data itself has changed.

**Comment by quinnj** [comment]
And perhaps this is stating the obvious, but the easy work-around here is to just call `CSV.read(...; delim=',')`; i.e. explicitly provide the delim. The auto-delimiter detection algorithm will get better and better over time, but if you know the delimiter, it's always safest to provide it yourself.

**Comment by jo-fleck** [comment]
Many thanks for looking so carefully into this @quinnj - much appreciated!

I’ve experimented a bit myself and arrive at the same conclusion: the problem occurs only when uploading a data frame with two rows so a change in the return data messes up the delimiter detection and the CSV update is just coincidental. I’ll reach out to the server admin and ask for clarification.

I'll make the delimiter explicit (as you suggest) so hopefully the program will be robust to any similar future changes in the return data. 

Thanks again! I'll close this for now.
