### ISSUE TITLE
Make validation on `types` parameter optional

### ISSUE THREAD

**Issue by AayushSabharwal** [JuliaData/CSV.jl#910]
#870 added validation to the `types` keyword, specifically requiring that all keys in the `Dict` also be columns in the CSV file.

It would be nice if such checking was optional, since it allows specifying types for _possible_ columns in a CSV. This is what we do in https://github.com/JuliaDynamics/Agents.jl/blob/master/src/submodules/io/csv_integration.jl, by analysing the field names of the agent struct to guess the columns and types in the CSV file. All the columns that are "guessed" may not appear in the CSV file.

Alternatively, is there a way to find the column names in the file from `CSV.Rows`? That would allow filtering the keys, and removing ones that aren't columns.

Ping https://github.com/JuliaDynamics/Agents.jl/pull/550

**Comment by nickrobinson251** [comment]
I think this would be a fairly easy addition, if we were happy to add yet another keyword argument (as discussed in https://github.com/JuliaData/CSV.jl/issues/802#issuecomment-847894430). There is already a `strict::Bool=false` keyword that controls whether or not _parsing_ will error on an invalid value. And i think we'd probably want to keep that keyword for controlling parsing, and introduce another one for validating the user-provided arguments, perhaps `validate::Bool=true` and then just change the code added in #870 to be `validate && checkinvalidcolumns(...)` and maybe to mention the `validate` keyword in the error message. Let's see what @quinnj prefers here. 

I definitely think it's a fairly common situation to have a list of _possible_ columns in a CSV (which might be a superset of actual columns in any given file), so i think it would be good to support passing such a list to `types`/`dateformat`/`pool`. And i think i agree that emitting a warning when this happens is annoying (since a user can be doing it knowingly on purpose, https://github.com/JuliaData/CSV.jl/issues/802#issuecomment-847845200).
