### ISSUE TITLE
Warnings when reading csv file

### ISSUE THREAD

**Issue by gitboy16** [JuliaData/CSV.jl#921]
I get a lot of warning when reading a csv file:
https://www.bde.es/webbde/en/estadis/pf/pf_es.csv
Html version can be found at
https://www.bde.es/webbde/en/estadis/pf/pf_es.html
Excel reads it correctly but the dataframe i get is messed up.
Is something wrong with the csv or CSV.jl?

**Comment by quinnj** [comment]
Yeah, it looks like the auto-delimiter detection gets confused and can't figure out that the delimiter should be `','` instead of `' '`. Another issue is that there are only 6 column names, but each row as 7 values (which CSV.jl correctly adjusts for). The final issue is that each row has like 800-1000 spaces that come after the final value. CSV.jl correctly ignores those spaces, but the 6th column name gets messed up because it includes those spaces, so doing the following gets a pretty legible DataFrame for me:
```julia
julia> df = CSV.read(file, DataFrame; delim=',', normalizenames=true)
```
