### ISSUE TITLE
Are ignored columns still parsed?

### ISSUE THREAD

**Issue by ShuhuaGao** [JuliaData/CSV.jl#942]
Consider the following MWE.
```julia
julia> using CSV

julia> data = """
       name, age
       Jack, 12
       Tom, 10
       """
"name, age\nJack, 12\nTom, 10\n"

julia> CSV.read(IOBuffer(data), Tuple; select=[2], types=Dict(2=>Int32))
(Int32[12, 10],)

julia> CSV.read(IOBuffer(data), Tuple; select=[2], types=Int32)
┌ Warning: thread = 1 warning: error parsing Int32 around row = 1, col = 1: "Jack,", error=INVALID: SENTINEL | DELIMITED | INVALID_DELIMITER 
└ @ CSV ~/.julia/packages/CSV/nofYz/src/file.jl:637
┌ Warning: thread = 1 warning: error parsing Int32 around row = 2, col = 1: "Tom,", error=INVALID: SENTINEL | DELIMITED | INVALID_DELIMITER 
└ @ CSV ~/.julia/packages/CSV/nofYz/src/file.jl:637
(Int32[12, 10],)
```
In the second `read` above, since I have only selected column 2, a natural expectation is that only column 2 is parsed. In other words, I expect that `types=Int32` applies to all *select* columns. However, it seems that column 1 is still parsed.

**Comment by nickrobinson251** [comment]
> Are ignored columns still parsed?

Yes, even with `select` (or `drop`), all columns are parsed initially, and then only afterwards dropped.

e.g. here's where they get dropped (immediately after parsing)
https://github.com/JuliaData/CSV.jl/blob/a68bb04877100fbbb6b98d2cee7e9dd8c1efd007/src/file.jl#L312-L322

(If i had to guess at why we parse them all, i'd guess it's because in multi-threaded parsing it's too hard to do the alternative of "ignoring" columns... but that's a guess)

But even taking for granted that's how thngs are implemented, I think this a good point:

>  I expect that `types=Int32` applies to all _select_ columns.

For example, we might be able to do something where we if we get `types::Type{T}` and `select`/`drop`, we expand `types` to be e.g. `Dict(i => T for i in select)` or `typesf(i, name) = i in select ? T : nothing` 🤔

**Comment by ShuhuaGao** [comment]
Many thanks for the explanation. That makes sense if "it's too hard to do the alternative of "ignoring" columns" in multi-threading.

**Comment by quinnj** [comment]
Thanks for the report @ShuhuaGao; this is just an oversight in our parsing code when the `types` keyword is provided along with `select`/`drop`. A fix is up here: https://github.com/JuliaData/CSV.jl/pull/943
