### ISSUE TITLE
Slow CSV reading when using multiple threads

### ISSUE THREAD

**Issue by bkamins** [JuliaData/CSV.jl#950]
* Start Julia with 4 threads.
* Download and uncompress file: https://database.lichess.org/lichess_db_puzzle.csv.bz2 to file puzzles.csv
* add a header to the csv file it `"PuzzleId,FEN,Moves,Rating,RatingDeviation,Popularity,NbPlays,Themes,GameUrl"` (this can be skipped but things are cleaner then)

Now you have (after compilation):
```
julia> @time CSV.read("puzzles.csv", DataFrame);
 44.654125 seconds (6.32 M allocations: 1.509 GiB)
```
vs
```
julia> @time CSV.read("puzzles.csv", DataFrame; ntasks=1);
  6.116780 seconds (6.16 M allocations: 1.037 GiB, 13.78% gc time)
```

**Comment by zsz00** [comment]
I meet the same problem today

**Comment by MichaelHatherly** [comment]
We've been encountering similar timings to those listed above when upgrading a code base from `0.8.5` to `0.9.*`. This appears to be a regression compared to `0.8.5` as shown in the comparisons below:

```
julia> @time CSV.read("lichess_db_puzzle.csv", DataFrame; tasks = 4);
  0.344046 seconds (10.67 M allocations: 713.270 MiB)

julia> @time CSV.read("lichess_db_puzzle.csv", DataFrame; threaded = false);
  1.744118 seconds (10.67 M allocations: 729.712 MiB, 41.06% gc time)

(jl_mYgSdE) pkg> st
      Status `/tmp/jl_mYgSdE/Project.toml`
  [336ed68f] CSV v0.8.5
  [a93c6f00] DataFrames v1.3.0
```

```
julia> @time CSV.read("lichess_db_puzzle.csv", DataFrame; ntasks = 4);
 72.317096 seconds (6.32 M allocations: 1.509 GiB)

julia> @time CSV.read("lichess_db_puzzle.csv", DataFrame; ntasks = 1);
  7.386177 seconds (4.03 M allocations: 1.577 GiB, 11.94% gc time)

(jl_ZKmI4e) pkg> st
      Status `/tmp/jl_ZKmI4e/Project.toml`
  [336ed68f] CSV v0.9.11
  [a93c6f00] DataFrames v1.3.0
```

The particular input files doesn't appear to matter much and it exhibits similar regressions with various CSV files. Even single threaded performance appears to have regressed here, just not to the same degree.

Initial latency (TTFR) appears to have regressed as well. Not sure though whether it's the same underlying cause perhaps (can open a separate issue to track that if needed):

```
julia> @time CSV.read("lichess_db_puzzle.csv", DataFrame; tasks = 4);
 14.640741 seconds (37.69 M allocations: 2.044 GiB, 7.07% gc time, 53.85% compilation time)

(jl_MUnrMy) pkg> st
      Status `/tmp/jl_MUnrMy/Project.toml`
  [336ed68f] CSV v0.8.5
  [a93c6f00] DataFrames v1.3.0
```

```
julia> @time CSV.read("lichess_db_puzzle.csv", DataFrame; ntasks = 4);
121.992381 seconds (14.81 M allocations: 1.968 GiB, 0.89% gc time)

(jl_hClxbq) pkg> st
      Status `/tmp/jl_hClxbq/Project.toml`
  [336ed68f] CSV v0.9.11
  [a93c6f00] DataFrames v1.3.0
```

A large chunk of that 121 seconds is clearly part of the first issue, but there does seem to be a noticeable amount aside from that.

**Comment by quinnj** [comment]
If anyone has time to do some quick profiling that could be helpful; using `Profile` and `@profile` and figuring out if there are certain code paths that are extremely different in 0.8 vs 0.9 or even just single-threaded vs. multithreaded. I personally enjoy using StatProfilerHTML with the visual outputs. I'm pretty tied up for the next day or two, but then should be able to help fix this.

**Comment by MichaelHatherly** [comment]
Attached are some profiles from the same four cases timed above: [profiles.tar.gz](https://github.com/JuliaData/CSV.jl/files/7726041/profiles.tar.gz)

**Comment by zsz00** [comment]
Has this problem been fixed??

**Comment by quinnj** [comment]
Ok, started digging into this; it's due to our change in how we determine whether columns should be pooled or not. The old method in 0.8 only looked at hte first 100 or so rows and then did a calculation about whether it should continue parsing the column as pooled or not.

The 0.9 method does full parsing assuming the column may be pooled and then reconciles post-parsing. The issue is that the 8th column in this dataset ends up having ~35K unique values, which is prohibitive performance-wise when considering normal PooledArray usage, but falls under the default 25% cardinality rule because there are 2.1M rows total.

So it seems to me that we need a more nuanced way of considering whether a column should be pooled or not; perhaps the `pool` argument should provide the total # of unique values under which the column will be pooled? But that makes it a bit tricky around deciding what the default value should be and whether it should be different for small vs. large files. It seems to me that we should probably consider some kind of logarithmic function to determine by default; something like `log(num_rows) * 10`, which would give the following thresholds:
 ```
 julia> pool(x) = log(x) * 10
pool (generic function with 1 method)

julia> for x in (100, 1_000, 100_000, 10_000_000)
       @show pool(x)
       end
pool(x) = 46.05170185988092
pool(x) = 69.07755278982137
pool(x) = 115.12925464970229
pool(x) = 161.1809565095832
 ```
Perhaps there's a better function to capture the right scaling, but I'm just not sure we should ever be pooling beyond a couple hundred values at the most.

Thoughts @bkamins/ @nalimilan or anyone else?

**Comment by bkamins** [comment]
There are two considerations here:
1. What should be the default behavior: here I would be even OK with some hard threshold, e.g. min(1000, 25% cardinality).
2. How to make sure that multi-threaded file reading is most efficient when user explicitly asks to pool data and it has high cardinality. Maybe we should not do per-thread pooling, but only pool it after reading in all data?

**Comment by quinnj** [comment]
Good distinction. Here's a sketch of what I want to try out:
  * if a column is user-requested to be pooled and non-string, we'll parse the column as-is, then pool afterwards (assuming it passes the threshold)
  * if column is inlinestring/poslenstring and pool is default or user-requested, we'll parse as inlinestring/poslenstring and pool afterwards
  * if column is string and pool is default or user-requested, we'll parse as `PosLen` column (memory efficient because it's 64 bits), then post parsing, we'll do pool threshold check by converting PosLen -> PointerString (CSV.jl internal string type for efficient memory hashing/comparison).
  
The reasoning for this strategy is as follows:
  * it's a tad less efficient _while parsing_ to build up a pool dict for a column that _might_ be pooled; post-parsing, the `syncrefs!` routine is cumbersome and is pretty complex code that ends up being a performance hit as noted above w/ high cardinality. 
  * So it's more efficient _while parsing_ to just parse regular column values: Int64, String7, etc. and I think it'll be pretty efficient to build the dict pool post-parsing, especially given the concurrency obstacles we face anyway by building pool dicts from each thread while parsing
  * For `stringtype=String`, it would certainly be _less_ efficient to allocate a ton of strings _while parsing_ if we end up wanting to pool afterwards, so that's why we'd utilize `PosLen` and do the pool dict build post-parsing where we use `PointerString` for an efficient hash check 

The piece I'm not quite certain on is the performance tradeoff of our current approach (build dict per thread while parsing, syncrefs post-parsing) vs. proposed approach (parse columns normal while parsing, check cardinality & build pool dict post-parsing), but my gut says they probably come out about even, since I know parsing columns normal is a tad faster than building pool dicts while parsing, while building full pool dict post-parsing is probably slower than our current syncrefs routine.

As long as the performance is roughly equal, the new proposed approach would be desirable since it simplifies a lot of core parsing code, while probably also being a bit simpler in terms of post-parsing processing.

**Comment by bkamins** [comment]
> converting PosLen -> PointerString

Cannot we at the very end convert `PointerString` to `String`?

**Comment by nalimilan** [comment]
If parsing as `PosLen` and pooling afterwards is reasonably fast, that sounds like a good and simpler solution. I have no idea about that but benchmarking will tell.

Though I'm not sure I understand the root cause of the slowdown described above. When you say:

> The 0.9 method does full parsing assuming the column may be pooled and then reconciles post-parsing. The issue is that the 8th column in this dataset ends up having ~35K unique values, which is prohibitive performance-wise when considering normal PooledArray usage, but falls under the default 25% cardinality rule because there are 2.1M rows total.

The unwritten assumption seems to be that high cardinality kills performance, which isn't obvious to me. I would have expected that high cardinality in absolute terms isn't a problem as long as the proportion of unique values is low, i.e. that the gain due to pooling is relative to the number of rows. But I'm probably missing something.

**Comment by quinnj** [comment]
> The unwritten assumption seems to be that high cardinality kills performance, which isn't obvious to me. I would have expected that high cardinality in absolute terms isn't a problem as long as the proportion of unique values is low, i.e. that the gain due to pooling is relative to the number of rows. But I'm probably missing something.

The problem with high cardinality really manifests in the `syncrefs!` routine, where we do, for each pooled column, for each threaded chunk:
  * loop through each unique value, check if it's ref code matches the "reference" pool
  * most of the time, the ref values don't match, so we have to loop over every value in that threaded chunk and recode the ref value with the "reference" value
So for the original file in question, on my machine with 8 threads, each chunk parses ~275K rows, and has some ~35K unique values that have to be recoded. The other sticking point is that we can't parallelize the ref syncing; i.e. because we have a single "reference" pool that each thread has to sync with sequentially. And that's already in addition to the slight performance hit by inserting each parsed value into a thread-local pool dict.

In the proposed approach, we only loop through each column value in a single pass to build the pool dict post-parsing.

I just got all tests passing w/ the new approach and I've got to say, I think it'll be a huge win just for the code simplification. Not having to deal w/ pooling during parsing ends up being a huge win in terms of code complexity. I haven't quite finished the optimization of treating possibly-pooled String columns as `PosLen` yet, but even still, the performance is very good, even without putting an upper limit on pool cardinality. I was wondering if we should just add a new keyword argument like `poollimit=500` where we won't pool a column if the total number of unique values is greater than it. Thoughts? Is that a good name for it? We could also or alternatively support passing a function for this keyword arg that would take the total # of rows and # of unique values as arguments? Or is that overkill?

**Comment by quinnj** [comment]
> Cannot we at the very end convert `PointerString` to `String`?

Yes, sorry for not finishing the thought completely, but yes, we would then convert to `String` at the end. The use of `PosLen` would be for efficiency while parsing, and `PointerString` while pool building (both help avoid intermediate allocations), and ultimately each time we find a new unique value, that's when we finally allocate the `String` value to put in the pool.

**Comment by quinnj** [comment]
To finish the thought on including a new `poollimit` keyword argument:
  * it would allow "short circuiting" when checking a column to be pooled post-parsing; once we hit the limit, we could bail on pool building and avoid the extra cost of building a pool with potentially a lot of unique values
  * Would it be too surprising for users sometimes though? Like, they request a column to be pooled, but don't know of/forget about `poollimit` and the column ends up not being pooled because the # of uniques values is > than `poollimit`. Perhaps if `pool=true` is passed, it would override any `poollimit` and pool unconditionally?

**Comment by bkamins** [comment]
> Perhaps if `pool=true` is passed, it would override any `poollimit` and pool unconditionally?

This is what I would expect as a user (the same if some column is explicitly asked to be pooled).

**Comment by nalimilan** [comment]
Thanks for the explanation. Then I agree that only pooling at the end is a good solution since you say it's relatively fast.

But I don't really understand why `poollimit` would be needed in that case. If pooling happens at the end, cardinality is no longer a problem, right? As you note, the increased complexity of the API would be annoying (proportion vs number).

**Comment by quinnj** [comment]
Well, an update here; all tests passing and I'm trying the parse-String-as-PosLen optimization, but it's proving tricky. The problem is still high cardinality at the end because it becomes really expensive to build large dicts and the rehashing costs end up swamping all other performance gains. So it was actually faster to parse the entire column as String, then use the new normal path of just building a dict from there. I'm going to take a step back and try to think about what we can do here.

**Comment by quinnj** [comment]
Ok, PR is up: https://github.com/JuliaData/CSV.jl/pull/962. Instead of adding a new keyword argument, I realized we could potentially allow passing a value greater than 1 for the `pool` argument to indicate an absolute upper limit on # of unique values. That seems to resolve my biggest concern, which was having this other "hidden" pool-related keyword arg that might affect pooling in addition to `pool`. I'd appreciate feedback if people think we're overloading the `pool` keyword arg too much though by introducing yet another possibility of what you can pass (i.e. a bool, Float64 between 0.0 and 1.0, number > 1, vector, dict, or function, 😅 ).

Ultimately, being able to have this upper limit threshold, and have it as the default, means we can be really efficient/performant in the default case, by short-circuiting the pool calculation check by not having to build a full pool just to throw it away because there are too many unique values.

**Comment by zsz00** [comment]
I take a test continuewith:
https://github.com/JuliaData/CSV.jl/issues/950#issuecomment-994591527

ubuntu 16.04, mem: 128G
my data: 150million rows, 9cols.

export JULIA_NUM_THREADS=20

````julia
CSV.jl  0.9.11
julia> @time node_info_1 = DataFrame(CSV.File(file_path));   # ntasks=20
3272.354131 seconds (341.04 M allocations: 98.706 GiB, 75.81% gc time, 4.30% compilation time)
julia> @time node_info_1 = DataFrame(CSV.File(file_path, ntasks=1));
1115.779001 seconds (262.11 M allocations: 48.603 GiB, 60.48% gc time, 13.50% compilation time)

CSV.jl  0.10.0
julia> @time node_info_1 = DataFrame(CSV.File(file_path));   # ntasks=20
446.860903 seconds (509.90 M allocations: 53.198 GiB, 28.26% gc time, 22.72% compilation time)
julia> @time node_info_1 = DataFrame(CSV.File(file_path; ntasks=1));
920.977022 seconds (499.38 M allocations: 51.762 GiB, 76.95% gc time, 11.77% compilation time)

```
There was a big increase in speed. 
The memory footprint is a little high.
