### ISSUE TITLE
Option to strip whitespace from strings

### ISSUE THREAD

**Issue by tp2750** [JuliaData/CSV.jl#951]
It would be good to have an option to strip leading and trailing whitespace from text columns.

This us useful if the input table has been padded to make the delimiters line up (eg orgmode tables). 

Currently we have:

```{julia}
data = """
| Name |  Zip |
| Joe  |  123 |
| Anne | 1234 |
"""
CSV.File(IOBuffer(data); delim='|', normalizenames=true)
2-element CSV.File:
 CSV.Row: (Column1 = missing, Name = " Joe  ", Zip = 123, Column4 = missing)
 CSV.Row: (Column1 = missing, Name = " Anne ", Zip = 1234, Column4 = missing)
```

It would be great to be able to add a keyword option like "stripwitespace=true" and get

```{julia}
data = """
| Name |  Zip |
| Joe  |  123 |
| Anne | 1234 |
"""
CSV.File(IOBuffer(data); delim='|', normalizenames=true, stripwhitespace=true)
2-element CSV.File:
 CSV.Row: (Column1 = missing, Name = "Joe", Zip = 123, Column4 = missing)
 CSV.Row: (Column1 = missing, Name = "Anne", Zip = 1234, Column4 = missing)
```

In R this is similar to `strip.white=TRUE` in `read.table()`

Conceptually, this would be applying `strip()` to all string elements.

I'll be happy to try to implement this, if it is found useful, and I can get a bit of guidance.

**Comment by quinnj** [comment]
Yeah, this shouldn't be too hard to support. The change would come in Parsers.jl. We could add a new "option" to the `Parsers.Options` struct to strip whitespace for strings (we already strip whitespace by default for non-strings). Then the implementation would happen in [this file](https://github.com/JuliaData/Parsers.jl/blob/main/src/strings.jl#L3). You'll notice there's already some code around stripping leading whitespace and that's because if we have a string like `  " abc " `, the leading/trailing whitespace before/after the double quotes will be stripped, while the "inner" whitespace (the single spaces before/after `abc`) will be preserved. So we would just want to check if `options.stripwhitespace` and then reset `vstartpos` to `pos` after we've stripped whitespace.

Thanks for the report and offer to help!

**Comment by tp2750** [comment]
Thanks for the hints @quinnj . I'll give it a shot.

**Comment by tp2750** [comment]
I think I've fixed it :smile: 

At least the tests of CSV are all green after I added these 2:

```
data = """
| Name       |  Zip |
| Joe        |  123 |
| Mary Anne  | 1234 |
"""
f = CSV.File(IOBuffer(data); delim='|', normalizenames=true, stripwhitespace=false)
@test f.Name[1] == " Joe        "
f = CSV.File(IOBuffer(data); delim='|', normalizenames=true, stripwhitespace=true)
@test f.Name[2] == "Mary Anne"
```

I'll make pull requests to both Parsers.jl and CSV.jl tomorrow.

**Comment by tp2750** [comment]
Thanks for your help @quinnj !
I've sent pull requests to Parsers.jl ([Parsers/104](https://github.com/JuliaData/Parsers.jl/pull/104)) and CSV.jl ([CSV/953](https://github.com/JuliaData/CSV.jl/pull/953)) referencing this issue. They do what I need.
Please review. 
It scares me a bit to work on performance sensitive code like this, so please look carefully :smile: 

- [X] Tests are added to CSV.jl, and both pull requests are needed to make the tests run.
- [X] The new option is added to the API documentation in `keyworddocs.jl` (CSV.jl) and `Parsers.Options`.

I realize now, that the commit messages are a bit terse. I'll be happy to write a proper commit message, if you decide to merge it.

**Comment by newptcai** [comment]
This does not seem to have been released. But some how it ends up in the documents already.

**Comment by quinnj** [comment]
This should indeed already be released.
